/**
 * Fetch YouTube highlights for all World Cup knockout matches (all years).
 *
 * Requires YOUTUBE_API_KEY in the environment and scripts/matches.json
 * (generated by scripts/extract-matches.ts).
 *
 * Usage: npx tsx scripts/extract-matches.ts > scripts/matches.json
 *        YOUTUBE_API_KEY=... npx tsx scripts/fetch-highlights.ts
 */
const API_KEY = process.env.YOUTUBE_API_KEY;
if (!API_KEY) {
  console.error("YOUTUBE_API_KEY not set");
  process.exit(1);
}

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

interface MatchEntry {
  year: number;
  round: string;
  key: string;
  teamA: string;
  teamB: string;
}

interface Highlight {
  videoId: string;
  title: string;
  thumbnail: string;
}

// Comprehensive team name mapping extracted from TEAMS in data.ts
const TEAM_NAME: Record<string, string> = {
  ALG: "Algeria",       ARG: "Argentina",     AUS: "Australia",
  AUT: "Austria",       BEL: "Belgium",       BIH: "Bosnia-Herz.",
  BOL: "Bolivia",       BRA: "Brazil",        BUL: "Bulgaria",
  CAN: "Canada",        CHI: "Chile",         CIV: "Côte d'Ivoire",
  CMR: "Cameroon",      COD: "DR Congo",      COL: "Colombia",
  CPV: "Cape Verde",    CRC: "Costa Rica",    CRO: "Croatia",
  CUB: "Cuba",          CUW: "Curaçao",       CZE: "Czech Republic",
  DEN: "Denmark",       ECU: "Ecuador",       EGY: "Egypt",
  ENG: "England",       ESP: "Spain",         FRA: "France",
  FRG: "West Germany",  GDR: "East Germany",  GER: "Germany",
  GHA: "Ghana",         GRE: "Greece",        HAI: "Haiti",
  HON: "Honduras",      HUN: "Hungary",       IDN: "Dutch East Indies",
  IRL: "Rep. Ireland",  IRN: "Iran",          IRQ: "Iraq",
  ISR: "Israel",        ITA: "Italy",         JOR: "Jordan",
  JPN: "Japan",         KOR: "South Korea",   KSA: "Saudi Arabia",
  KUW: "Kuwait",        MAR: "Morocco",       MEX: "Mexico",
  NED: "Netherlands",   NGA: "Nigeria",       NIR: "Northern Ireland",
  NOR: "Norway",        NZL: "New Zealand",   PAN: "Panama",
  PAR: "Paraguay",      PER: "Peru",          POL: "Poland",
  POR: "Portugal",      PRK: "North Korea",   QAT: "Qatar",
  ROU: "Romania",       RSA: "South Africa",  RUS: "Russia",
  SCO: "Scotland",      SEN: "Senegal",       SLV: "El Salvador",
  SUI: "Switzerland",   SVK: "Slovakia",      SWE: "Sweden",
  TCH: "Czechoslovakia", TUN: "Tunisia",      TUR: "Türkiye",
  UKR: "Ukraine",       URS: "Soviet Union",  URU: "Uruguay",
  USA: "USA",           UZB: "Uzbekistan",    WAL: "Wales",
  YUG: "Yugoslavia",    ZAI: "Zaire",
};

async function searchYouTube(query: string): Promise<Highlight | null> {
  const url = new URL("https://www.googleapis.com/youtube/v3/search");
  url.searchParams.set("part", "snippet");
  url.searchParams.set("q", query);
  url.searchParams.set("type", "video");
  url.searchParams.set("maxResults", "1");
  url.searchParams.set("key", API_KEY!);
  url.searchParams.set("relevanceLanguage", "en");
  url.searchParams.set("videoEmbeddable", "true");

  const res = await fetch(url.toString());
  if (!res.ok) {
    console.error(`  YouTube API ${res.status}: ${(await res.text()).slice(0, 200)}`);
    return null;
  }
  const data = (await res.json()) as any;
  const item = data.items?.[0];
  if (!item) return null;

  const videoId: string = item.id.videoId;
  const thumbs = item.snippet.thumbnails ?? {};
  return {
    videoId,
    title: item.snippet.title,
    thumbnail: thumbs.maxres?.url ?? thumbs.high?.url ?? thumbs.medium?.url ?? "",
  };
}

async function main() {
  const matchesPath = resolve((import.meta as any).dirname ?? __dirname, "..", "scripts", "matches.json");
  const outFile = resolve((import.meta as any).dirname ?? __dirname, "..", "src", "highlights.ts");
  const matches: MatchEntry[] = JSON.parse(readFileSync(matchesPath, "utf-8"));

  // Resume: load existing highlights so we don't re-fetch.
  const existing: Record<string, Highlight> = {};
  try {
    const old = readFileSync(outFile, "utf-8");
    // Extract entries with a quick regex — avoid parsing the full TS module.
    for (const m of old.matchAll(/"(\d{4}_\w+_\w+)":\s*\{\s*videoId:\s*"([^"]+)",\s*title:\s*"((?:[^"\\]|\\.)*)",\s*thumbnail:\s*"([^"]*)"/g)) {
      existing[m[1]] = { videoId: m[2], title: m[3], thumbnail: m[4] };
    }
  } catch {}

  const toFetch = matches.filter(m => !existing[m.key]);
  console.log(`${matches.length} total, ${Object.keys(existing).length} existing, ${toFetch.length} to fetch.\n`);

  if (toFetch.length === 0) {
    console.log("Nothing to do.");
    return;
  }

  const results: Record<string, Highlight> = { ...existing };
  let fetched = 0;
  let skipped = 0;

  for (const m of toFetch) {

    const nameA = TEAM_NAME[m.teamA] ?? m.teamA;
    const nameB = TEAM_NAME[m.teamB] ?? m.teamB;
    const query = `${nameA} ${nameB} ${m.year} World Cup highlights`;

    console.log(`[${m.year}] ${m.teamA} vs ${m.teamB}`);
    try {
      const hl = await searchYouTube(query);
      if (!hl) {
        console.log(`  -> no result`);
        skipped++;
        continue;
      }
      results[m.key] = hl;
      fetched++;
      console.log(`  -> ${hl.videoId}: ${hl.title.slice(0, 80)}`);
    } catch (err) {
      console.error(`  -> error: ${err}`);
    }
    await new Promise((r) => setTimeout(r, 500));
  }

  const entries = Object.entries(results)
    .map(([k, v]) =>
      `  "${k}": { videoId: ${JSON.stringify(v.videoId)}, title: ${JSON.stringify(v.title)}, thumbnail: ${JSON.stringify(v.thumbnail)} },`
    )
    .join("\n");

  const src = `// Auto-generated by scripts/fetch-highlights.ts — DO NOT EDIT BY HAND.
// Keyed \`\${year}_\${teamA}_\${teamB}\`. lookup tries both orientations.

export interface Highlight {
  videoId: string;
  title: string;
  thumbnail: string;
}

const HIGHLIGHTS: Record<string, Highlight> = {
${entries}
};

export function getHighlights(
  year: number,
  teamA: string,
  teamB: string
): Highlight | null {
  return (
    HIGHLIGHTS[\`\${year}_\${teamA}_\${teamB}\`] ??
    HIGHLIGHTS[\`\${year}_\${teamB}_\${teamA}\`] ??
    null
  );
}
`;

  const outFile = resolve((import.meta as any).dirname ?? __dirname, "..", "src", "highlights.ts");
  writeFileSync(outFile, src, "utf-8");

  console.log(`\n---`);
  console.log(`Fetched: ${fetched} | Skipped: ${skipped}`);
  console.log(`Wrote ${outFile}`);
}

main();
