// Build-time generator: fetches a small pool of football photos per World Cup
// champion nation from the Unsplash API and writes committed CDN URLs to
// src/championImages.generated.ts. The client then picks from that pool — no
// Unsplash key in the browser bundle, no per-visitor API calls, no rate limits.
//
// Run locally with the key available (reads VITE_UNSPLASH_ACCESS_KEY from .env
// or the environment):  npm run gen:champion-images
//
// Champions are fixed history, so this rarely needs re-running — only when a new
// nation wins (e.g. once the 2026 final is played, if the winner isn't listed).

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { getTeamName } from "../src/data";

// Every nation that has ever won the World Cup (keyed by the app's team code).
// FRA / ESP / ARG / ENG also cover every side still alive in 2026.
const CHAMPION_CODES = ["URU", "ITA", "FRG", "GER", "BRA", "ENG", "ARG", "FRA", "ESP"];

// West Germany → search plain "Germany" for better football imagery.
const QUERY_NAME: Record<string, string> = { FRG: "Germany" };

const FOOTBALL_KEYWORDS = [
  "soccer", "football", "stadium", "pitch", "jersey",
  "supporter", "fan", "goal", "match", "player", "crowd",
];
const UTM = "utm_source=the_road_to_glory&utm_medium=referral";
const POOL_SIZE = 5;

function accessKey(): string {
  if (process.env.VITE_UNSPLASH_ACCESS_KEY) return process.env.VITE_UNSPLASH_ACCESS_KEY;
  try {
    const env = readFileSync(resolve(process.cwd(), ".env"), "utf8");
    const m = env.match(/VITE_UNSPLASH_ACCESS_KEY\s*=\s*"?([^"\n]+)"?/);
    if (m) return m[1].trim();
  } catch {
    /* no .env */
  }
  throw new Error("VITE_UNSPLASH_ACCESS_KEY not set (in env or .env)");
}

const KEY = accessKey();

interface Photo {
  urls: { regular: string };
  alt_description: string | null;
  description: string | null;
  user?: { name?: string; links?: { html?: string } };
}
interface ImageMeta { url: string; alt: string; authorName: string; authorUrl: string; }

async function search(query: string): Promise<Photo[]> {
  const res = await fetch(
    `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}` +
      `&per_page=20&orientation=landscape&content_filter=high`,
    { headers: { Authorization: `Client-ID ${KEY}` } }
  );
  if (!res.ok) throw new Error(`Unsplash ${res.status} for "${query}"`);
  return ((await res.json()).results ?? []) as Photo[];
}

const score = (p: Photo) => {
  const text = `${p.alt_description ?? ""} ${p.description ?? ""}`.toLowerCase();
  return FOOTBALL_KEYWORDS.reduce((n, k) => (text.includes(k) ? n + 1 : n), 0);
};

const toMeta = (p: Photo): ImageMeta => ({
  url: p.urls.regular,
  alt: p.alt_description ?? "",
  authorName: p.user?.name ?? "Unsplash",
  authorUrl: `${p.user?.links?.html ?? "https://unsplash.com"}?${UTM}`,
});

async function poolFor(code: string): Promise<ImageMeta[]> {
  const name = QUERY_NAME[code] ?? getTeamName(code);
  let photos = (await search(`${name} football match`)).filter((p) => score(p) > 0);
  if (photos.length < POOL_SIZE) {
    // Top up with generic football imagery so every champion has a full pool.
    const generic = (await search("football stadium crowd")).filter((p) => score(p) > 0);
    photos = [...photos, ...generic];
  }
  // Highest football relevance first; keep a handful for variety.
  return photos.sort((a, b) => score(b) - score(a)).slice(0, POOL_SIZE).map(toMeta);
}

async function main() {
  const out: Record<string, ImageMeta[]> = {};
  for (const code of CHAMPION_CODES) {
    const pool = await poolFor(code);
    out[code] = pool;
    console.log(`${code}: ${pool.length} images`);
  }

  const body =
    `// GENERATED by scripts/generate-champion-images.ts — do not edit by hand.\n` +
    `// Champion hero photos from Unsplash (${new Date().toISOString().slice(0, 10)}),\n` +
    `// committed as CDN URLs so production needs no Unsplash key. Re-run:\n` +
    `//   npm run gen:champion-images\n\n` +
    `export interface ChampionImage {\n` +
    `  url: string;\n  alt: string;\n  authorName: string;\n  authorUrl: string;\n}\n\n` +
    `export const CHAMPION_IMAGES: Record<string, ChampionImage[]> = ${JSON.stringify(out, null, 2)};\n`;

  const outPath = resolve(process.cwd(), "src", "championImages.generated.ts");
  writeFileSync(outPath, body);
  console.log(`\nWrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
