// Build-time generator: pulls simple country outline SVGs from mapsicon
// (github.com/djaiss/mapsicon, public domain) and commits their path data to
// src/countryMaps.generated.ts. The <CountryMap> component then strokes the
// outline with a glowing draw-in animation. No runtime deps or fetches.
//
//   npm run gen:country-maps
//
// Historical nations resolve to their modern outline (West Germany → Germany,
// USSR → Russia, Yugoslavia → Serbia, Czechoslovakia → Czechia, Zaire → DR Congo).

import { writeFileSync } from "fs";
import { resolve } from "path";

// App team code → ISO 3166-1 alpha-2 (mapsicon folder). England has no separate
// outline in the set, so it borrows the UK ("gb"). Historical nations map to
// their modern successor.
const ISO2: Record<string, string> = {
  ALG: "dz", ARG: "ar", AUS: "au", AUT: "at", BEL: "be", BIH: "ba",
  BOL: "bo", BRA: "br", BUL: "bg", CAN: "ca", CHI: "cl", CIV: "ci",
  CMR: "cm", COD: "cd", COL: "co", CPV: "cv", CRC: "cr", CRO: "hr",
  CUB: "cu", CUW: "cw", CZE: "cz", DEN: "dk", ECU: "ec", EGY: "eg",
  ENG: "gb", ESP: "es", FRA: "fr", GHA: "gh", GRE: "gr", HAI: "ht",
  HON: "hn", HUN: "hu", IDN: "id", IRL: "ie", IRN: "ir", IRQ: "iq",
  ISR: "il", ITA: "it", JOR: "jo", JPN: "jp", KOR: "kr", KSA: "sa",
  KUW: "kw", MAR: "ma", MEX: "mx", NED: "nl", NGA: "ng", NIR: "gb",
  NOR: "no", NZL: "nz", PAN: "pa", PAR: "py", PER: "pe", POL: "pl",
  POR: "pt", PRK: "kp", QAT: "qa", ROU: "ro", RSA: "za", RUS: "ru",
  SCO: "gb", SEN: "sn", SLV: "sv", SUI: "ch", SVK: "sk", SWE: "se",
  TUN: "tn", TUR: "tr", UKR: "ua", URU: "uy", USA: "us", UZB: "uz",
  WAL: "gb",
  FRG: "de", GDR: "de", GER: "de",
  TCH: "cz", URS: "ru", YUG: "rs", ZAI: "cd",
};

// All nation codes that appear in tournament data (skipping TBD).
const CODES = Object.keys(ISO2).sort();

// Extra territories to merge into a nation's map outline (e.g. Western Sahara
// included in Morocco). The extra paths share the host's transform.
const EXTRA_TERRITORIES: Record<string, string[]> = {
  MAR: ["eh"],
};

interface CountryMap { transform: string; paths: string[]; }

async function fetchMap(iso2: string): Promise<CountryMap> {
  const res = await fetch(`https://raw.githubusercontent.com/djaiss/mapsicon/master/all/${iso2}/vector.svg`);
  if (!res.ok) throw new Error(`mapsicon ${res.status} for ${iso2}`);
  const svg = await res.text();
  const transform = svg.match(/transform="([^"]*)"/)?.[1] ?? "";
  const all = [...svg.matchAll(/<path[^>]*\bd="([^"]+)"/g)].map((m) => m[1]);
  if (all.length === 0) throw new Error(`no paths in ${iso2}`);
  // Keep the significant landmasses (largest first), dropping tiny specks — so
  // the draw isn't dominated by dozens of islets and stays a clean sequence.
  const sorted = [...all].sort((a, b) => b.length - a.length);
  const max = sorted[0].length;
  // Round coordinates to integers — the outline is scaled down 10× at render, so
  // sub-unit precision is invisible but nearly halves the committed size.
  const round = (d: string) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(parseFloat(n))));
  const paths = sorted.filter((d) => d.length >= max * 0.08).slice(0, 5).map(round);
  return { transform, paths };
}

async function main() {
  const out: Record<string, CountryMap> = {};
  for (const code of CODES) {
    const iso2 = ISO2[code];
    if (!iso2) { console.warn(`skip ${code}: no ISO2 mapping`); continue; }
    const map = await fetchMap(iso2);
    const extras = EXTRA_TERRITORIES[code];
    if (extras) {
      for (const extra of extras) {
        try {
          const em = await fetchMap(extra);
          map.paths.push(...em.paths);
          console.log(`  + ${extra} (${out[code]?.paths.length ?? map.paths.length - em.paths.length} → ${map.paths.length})`);
        } catch { console.warn(`  skip extra ${extra}: not available`); }
      }
    }
    out[code] = map;
    console.log(`${code} (${iso2}): ${map.paths.length} path(s)`);
  }

  const body =
    `// GENERATED by scripts/generate-country-maps.ts — do not edit by hand.\n` +
    `// Country outlines from mapsicon (public domain). viewBox is 0 0 1024 1024.\n\n` +
    `export interface CountryMap {\n  transform: string;\n  paths: string[];\n}\n\n` +
    `export const COUNTRY_MAPS: Record<string, CountryMap> = ${JSON.stringify(out, null, 2)};\n`;

  const outPath = resolve(process.cwd(), "src", "countryMaps.generated.ts");
  writeFileSync(outPath, body);
  console.log(`\nWrote ${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
