// GENERATED by scripts/generate-champion-images.ts — do not edit by hand.
// Champion hero photos from Unsplash (2026-07-12),
// committed as CDN URLs so production needs no Unsplash key. Re-run:
//   npm run gen:champion-images

export interface ChampionImage {
  url: string;
  alt: string;
  authorName: string;
  authorUrl: string;
}

export const CHAMPION_IMAGES: Record<string, ChampionImage[]> = {
  "URU": [
    {
      "url": "https://images.unsplash.com/photo-1706675780107-7c43cc487928?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxmb290YmFsbCUyMHN0YWRpdW0lMjBjcm93ZHxlbnwxfDB8fHwxNzgzODUyNDc2fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a soccer match in a stadium at night",
      "authorName": "Alex Simpson",
      "authorUrl": "https://unsplash.com/@m_simpsan?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1545525201-e1a5a2a18293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxM3x8Zm9vdGJhbGwlMjBzdGFkaXVtJTIwY3Jvd2R8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "soccer player standing on soccer field",
      "authorName": "Tobias",
      "authorUrl": "https://unsplash.com/@herrzett?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1714623352740-4e74442ad9fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxVcnVndWF5JTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc1fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a soccer player covers his face with his hands",
      "authorName": "Bruno Cal",
      "authorUrl": "https://unsplash.com/@brunooh?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1629217855633-79a6925d6c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHN0YWRpdW0lMjBjcm93ZHxlbnwxfDB8fHwxNzgzODUyNDc2fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people watching soccer game in stadium",
      "authorName": "Krzysztof Dubiel",
      "authorUrl": "https://unsplash.com/@kris1902?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1679391029864-d46f366a456b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwzfHxmb290YmFsbCUyMHN0YWRpdW0lMjBjcm93ZHxlbnwxfDB8fHwxNzgzODUyNDc2fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a soccer stadium filled with lots of people",
      "authorName": "Howard Bouchevereau",
      "authorUrl": "https://unsplash.com/@howardbouchevereau?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "ITA": [
    {
      "url": "https://images.unsplash.com/photo-1778426617106-c2666189e550?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxJdGFseSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Soccer players on a grassy field during a game.",
      "authorName": "Alex G",
      "authorUrl": "https://unsplash.com/@grizzlyil?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1778426678037-e18fcf2075f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxJdGFseSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Soccer players on a field during a game.",
      "authorName": "Alex G",
      "authorUrl": "https://unsplash.com/@grizzlyil?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1778426643374-2b86e718bae0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwzfHxJdGFseSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Soccer players on a grassy field during a game.",
      "authorName": "Alex G",
      "authorUrl": "https://unsplash.com/@grizzlyil?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1778426607959-61846cd23907?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw0fHxJdGFseSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Soccer players on a field seen through a fence.",
      "authorName": "Alex G",
      "authorUrl": "https://unsplash.com/@grizzlyil?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1625006981702-ef37d4eda8b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw2fHxJdGFseSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people in a concert during night time",
      "authorName": "Gabriella Clare Marino",
      "authorUrl": "https://unsplash.com/@gabiontheroad?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "FRG": [
    {
      "url": "https://images.unsplash.com/photo-1554301424-6f0991b07ea6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxMHx8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a large crowd of people watching a soccer game",
      "authorName": "Waldemar Brandt",
      "authorUrl": "https://unsplash.com/@waldemarbrandt67w?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1545525201-e1a5a2a18293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxNnx8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "soccer player standing on soccer field",
      "authorName": "Tobias",
      "authorUrl": "https://unsplash.com/@herrzett?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxN3x8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "high angel photography of football stadium",
      "authorName": "Mario Klassen",
      "authorUrl": "https://unsplash.com/@marioklassen?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1780746368913-9d501b42e3f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxHZXJtYW55JTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Smiling man in jersey walking near allianz arena stadium.",
      "authorName": "Omar Ramadan",
      "authorUrl": "https://unsplash.com/@omarvellous14?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1782355341384-def1cd846ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw0fHxHZXJtYW55JTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A stadium with large national flags and a cheering crowd.",
      "authorName": "Frank Huang",
      "authorUrl": "https://unsplash.com/@frankhme?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "GER": [
    {
      "url": "https://images.unsplash.com/photo-1554301424-6f0991b07ea6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxMHx8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a large crowd of people watching a soccer game",
      "authorName": "Waldemar Brandt",
      "authorUrl": "https://unsplash.com/@waldemarbrandt67w?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1545525201-e1a5a2a18293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxNnx8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "soccer player standing on soccer field",
      "authorName": "Tobias",
      "authorUrl": "https://unsplash.com/@herrzett?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxN3x8R2VybWFueSUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "high angel photography of football stadium",
      "authorName": "Mario Klassen",
      "authorUrl": "https://unsplash.com/@marioklassen?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1780746368913-9d501b42e3f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxHZXJtYW55JTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Smiling man in jersey walking near allianz arena stadium.",
      "authorName": "Omar Ramadan",
      "authorUrl": "https://unsplash.com/@omarvellous14?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1782355341384-def1cd846ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw0fHxHZXJtYW55JTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A stadium with large national flags and a cheering crowd.",
      "authorName": "Frank Huang",
      "authorUrl": "https://unsplash.com/@frankhme?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "BRA": [
    {
      "url": "https://images.unsplash.com/photo-1527154341204-319eeba2d06e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxCcmF6aWwlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "man wearing cap and jersey",
      "authorName": "Vinicius \"amnx\" Amano",
      "authorUrl": "https://unsplash.com/@viniciusamano?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1601087373050-0cb2aa6bf7ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwzfHxCcmF6aWwlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a close up of the logo on a soccer jersey",
      "authorName": "Alice Yamamura",
      "authorUrl": "https://unsplash.com/@aakemiy?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1716745558946-421223f8d785?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw3fHxCcmF6aWwlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "an overhead view of a basketball court in a park",
      "authorName": "João Pedro Schmitz",
      "authorUrl": "https://unsplash.com/@jpedroschmitz?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1571190894029-caa26b1f4c09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxCcmF6aWwlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "soccer ball on grass",
      "authorName": "Souza Sergio",
      "authorUrl": "https://unsplash.com/@sergiossouza?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1632184671130-f63ac80ec83b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw4fHxCcmF6aWwlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a crowd of people walking down a street",
      "authorName": "Matheus Câmara da Silva",
      "authorUrl": "https://unsplash.com/@matheussox?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "ENG": [
    {
      "url": "https://images.unsplash.com/photo-1777715330202-7a313be5fe3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw2fHxFbmdsYW5kJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A football stadium with sprinklers on the pitch.",
      "authorName": "Tanya Barrow",
      "authorUrl": "https://unsplash.com/@tanyabarrow?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1727873275022-d5189075c660?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxNnx8RW5nbGFuZCUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OHww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A stadium filled with lots of people watching a soccer game",
      "authorName": "Sierra Alpha Juliet",
      "authorUrl": "https://unsplash.com/@mrhz?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1577214250144-73af4b7364f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxFbmdsYW5kJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people in soccer stadium",
      "authorName": "Nelson Ndongala",
      "authorUrl": "https://unsplash.com/@whodunelson?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1626078859283-7e83d7e4137f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwzfHxFbmdsYW5kJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people watching football game on stadium",
      "authorName": "Samuel Regan-Asante",
      "authorUrl": "https://unsplash.com/@reganography?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1577214250705-d5c24d76ea0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxFbmdsYW5kJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people in soccer stadium",
      "authorName": "Nelson Ndongala",
      "authorUrl": "https://unsplash.com/@whodunelson?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "ARG": [
    {
      "url": "https://images.unsplash.com/photo-1596209949480-ddb7d40878f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxBcmdlbnRpbmElMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people in a stadium with blue and white curtains",
      "authorName": "Cristian Tarzi",
      "authorUrl": "https://unsplash.com/@ctarzi?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1671016233730-44258a88eb03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxM3x8QXJnZW50aW5hJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a close up of a soccer jersey with the word messi on it",
      "authorName": "磊 周",
      "authorUrl": "https://unsplash.com/@dwlly?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1671459622301-78cf3f419b61?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxBcmdlbnRpbmElMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a crowd of people standing around a man holding a basketball",
      "authorName": "Alvaro Palacios",
      "authorUrl": "https://unsplash.com/@xapalacioscx?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1596209949429-9b6068df436b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxBcmdlbnRpbmElMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "people on green grass field during daytime",
      "authorName": "Cristian Tarzi",
      "authorUrl": "https://unsplash.com/@ctarzi?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1671459621493-019af01dde32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw0fHxBcmdlbnRpbmElMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a crowd of people standing around each other",
      "authorName": "Alvaro Palacios",
      "authorUrl": "https://unsplash.com/@xapalacioscx?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "FRA": [
    {
      "url": "https://images.unsplash.com/photo-1676558571547-33a188628dd4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw4fHxGcmFuY2UlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a crowd of people watching a soccer game",
      "authorName": "Steven Collomb-Clerc",
      "authorUrl": "https://unsplash.com/@stevencclerc?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1679391029864-d46f366a456b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxM3x8RnJhbmNlJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a soccer stadium filled with lots of people",
      "authorName": "Howard Bouchevereau",
      "authorUrl": "https://unsplash.com/@howardbouchevereau?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1646350639591-e324c3e72b9c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxNXx8RnJhbmNlJTIwZm9vdGJhbGwlMjBtYXRjaHxlbnwxfDB8fHwxNzgzODUyNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "a large stadium filled with lots of people",
      "authorName": "Denise Jans",
      "authorUrl": "https://unsplash.com/@dmjdenise?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1778948700469-f919a9bd0567?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwyfHxGcmFuY2UlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Men playing soccer in a park",
      "authorName": "Kyle Hinkson",
      "authorUrl": "https://unsplash.com/@whereiskylenow?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1746250202757-e7ca7f02c131?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxGcmFuY2UlMjBmb290YmFsbCUyMG1hdGNofGVufDF8MHx8fDE3ODM4NTI0Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "People hold the olympic flag on a field.",
      "authorName": "Kaptured by Kasia",
      "authorUrl": "https://unsplash.com/@kasiade?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ],
  "ESP": [
    {
      "url": "https://images.unsplash.com/photo-1781152791873-ced9456b14ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwzfHxTcGFpbiUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "Football match in a brightly lit stadium at night.",
      "authorName": "Maryam Tello",
      "authorUrl": "https://unsplash.com/@tellophotography?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1766756467595-fd3f1f62d562?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw0fHxTcGFpbiUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A packed stadium with red and white supporters cheering fans.",
      "authorName": "Josip Ivanković",
      "authorUrl": "https://unsplash.com/@piak?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1540962800595-53f202608161?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw2fHxTcGFpbiUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "soccer player on stadium",
      "authorName": "Michael Lee",
      "authorUrl": "https://unsplash.com/@guoshiwushuang?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1504016798967-59a258e9386d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHwxfHxTcGFpbiUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "green soccer field with crowd at daytime",
      "authorName": "Liam McKay",
      "authorUrl": "https://unsplash.com/@liammckay?utm_source=the_road_to_glory&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1779408106765-0ddba466ceb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTY2NDB8MHwxfHNlYXJjaHw1fHxTcGFpbiUyMGZvb3RiYWxsJTIwbWF0Y2h8ZW58MXwwfHx8MTc4Mzg1MjQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
      "alt": "A large, empty football stadium with red advertising banners.",
      "authorName": "Corey Willett",
      "authorUrl": "https://unsplash.com/@coreyw2005?utm_source=the_road_to_glory&utm_medium=referral"
    }
  ]
};
