// AUTO-GENERATED by scripts/generate-country-stats.ts — DO NOT EDIT BY HAND.
// Source: jfjelstul/worldcup (MIT). FIFA Men's World Cup 1930–2022, group stage
// included. Shootout matches count as draws; pens tracked separately.

export interface CountryStats {
  record: { w: number; d: number; l: number; gf: number; ga: number; pensWon: number; pensLost: number };
  topScorers: { name: string; goals: number; span: string }[];
  rivalries: { code: string; played: number; w: number; d: number; l: number }[];
}

export const COUNTRY_STATS: Record<string, CountryStats> = {
  "ALG": {
    "record": {
      "w": 3,
      "d": 3,
      "l": 7,
      "gf": 13,
      "ga": 19,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Abdelmoumene Djabou",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Islam Slimani",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Salah Assad",
        "goals": 2,
        "span": "1982"
      },
      {
        "name": "Djamel Zidane",
        "goals": 1,
        "span": "1986"
      },
      {
        "name": "Lakhdar Belloumi",
        "goals": 1,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "FRG",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "CHI",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "KOR",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "AUT",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "ARG": {
    "record": {
      "w": 47,
      "d": 17,
      "l": 24,
      "gf": 152,
      "ga": 101,
      "pensWon": 6,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Lionel Messi",
        "goals": 13,
        "span": "2006–2022"
      },
      {
        "name": "Gabriel Batistuta",
        "goals": 10,
        "span": "1994–2002"
      },
      {
        "name": "Diego Maradona",
        "goals": 8,
        "span": "1982–1994"
      },
      {
        "name": "Guillermo Stábile",
        "goals": 8,
        "span": "1930"
      },
      {
        "name": "Mario Kempes",
        "goals": 6,
        "span": "1978"
      }
    ],
    "rivalries": [
      {
        "code": "NED",
        "played": 6,
        "w": 1,
        "d": 3,
        "l": 2
      },
      {
        "code": "NGA",
        "played": 5,
        "w": 5,
        "d": 0,
        "l": 0
      },
      {
        "code": "ENG",
        "played": 5,
        "w": 1,
        "d": 1,
        "l": 3
      },
      {
        "code": "ITA",
        "played": 5,
        "w": 0,
        "d": 3,
        "l": 2
      }
    ]
  },
  "AUS": {
    "record": {
      "w": 4,
      "d": 4,
      "l": 12,
      "gf": 17,
      "ga": 37,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Tim Cahill",
        "goals": 5,
        "span": "2006–2014"
      },
      {
        "name": "Mile Jedinak",
        "goals": 3,
        "span": "2014–2018"
      },
      {
        "name": "Brett Holman",
        "goals": 2,
        "span": "2010"
      },
      {
        "name": "Craig Goodwin",
        "goals": 1,
        "span": "2022"
      },
      {
        "name": "Craig Moore",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "DEN",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      },
      {
        "code": "CHI",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "FRA",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "JPN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "AUT": {
    "record": {
      "w": 12,
      "d": 4,
      "l": 13,
      "gf": 43,
      "ga": 47,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Erich Probst",
        "goals": 6,
        "span": "1954"
      },
      {
        "name": "Hans Krankl",
        "goals": 5,
        "span": "1978–1982"
      },
      {
        "name": "Alfred Körner",
        "goals": 3,
        "span": "1954–1958"
      },
      {
        "name": "Ernst Stojaspal",
        "goals": 3,
        "span": "1954"
      },
      {
        "name": "Theodor Wagner",
        "goals": 3,
        "span": "1954"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 4,
        "w": 0,
        "d": 0,
        "l": 4
      },
      {
        "code": "FRG",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "FRA",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "TCH",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      }
    ]
  },
  "BEL": {
    "record": {
      "w": 21,
      "d": 10,
      "l": 20,
      "gf": 69,
      "ga": 74,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Marc Wilmots",
        "goals": 5,
        "span": "1998–2002"
      },
      {
        "name": "Romelu Lukaku",
        "goals": 5,
        "span": "2014–2018"
      },
      {
        "name": "Jan Ceulemans",
        "goals": 4,
        "span": "1986–1990"
      },
      {
        "name": "Eden Hazard",
        "goals": 3,
        "span": "2018"
      },
      {
        "name": "Enzo Scifo",
        "goals": 3,
        "span": "1986–1990"
      }
    ],
    "rivalries": [
      {
        "code": "ENG",
        "played": 4,
        "w": 2,
        "d": 1,
        "l": 1
      },
      {
        "code": "KOR",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      },
      {
        "code": "URS",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "ARG",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      }
    ]
  },
  "BIH": {
    "record": {
      "w": 1,
      "d": 0,
      "l": 2,
      "gf": 4,
      "ga": 4,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Avdija Vršajević",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Edin Džeko",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Miralem Pjanić",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Vedad Ibišević",
        "goals": 1,
        "span": "2014"
      }
    ],
    "rivalries": [
      {
        "code": "IRN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "NGA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "BOL": {
    "record": {
      "w": 0,
      "d": 1,
      "l": 5,
      "gf": 1,
      "ga": 20,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Erwin Sánchez",
        "goals": 1,
        "span": "1994"
      }
    ],
    "rivalries": [
      {
        "code": "YUG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "URU",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "GER",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "BRA": {
    "record": {
      "w": 76,
      "d": 19,
      "l": 19,
      "gf": 237,
      "ga": 108,
      "pensWon": 3,
      "pensLost": 2
    },
    "topScorers": [
      {
        "name": "Ronaldo",
        "goals": 15,
        "span": "1998–2006"
      },
      {
        "name": "Pelé",
        "goals": 12,
        "span": "1958–1970"
      },
      {
        "name": "Ademir",
        "goals": 9,
        "span": "1950"
      },
      {
        "name": "Jairzinho",
        "goals": 9,
        "span": "1970–1974"
      },
      {
        "name": "Vavá",
        "goals": 9,
        "span": "1958–1962"
      }
    ],
    "rivalries": [
      {
        "code": "SWE",
        "played": 7,
        "w": 5,
        "d": 2,
        "l": 0
      },
      {
        "code": "MEX",
        "played": 5,
        "w": 4,
        "d": 1,
        "l": 0
      },
      {
        "code": "ESP",
        "played": 5,
        "w": 3,
        "d": 1,
        "l": 1
      },
      {
        "code": "TCH",
        "played": 5,
        "w": 3,
        "d": 2,
        "l": 0
      }
    ]
  },
  "BUL": {
    "record": {
      "w": 3,
      "d": 8,
      "l": 15,
      "gf": 22,
      "ga": 53,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Hristo Stoichkov",
        "goals": 6,
        "span": "1994"
      },
      {
        "name": "Hristo Bonev",
        "goals": 2,
        "span": "1970–1974"
      },
      {
        "name": "Nasko Sirakov",
        "goals": 2,
        "span": "1986–1994"
      },
      {
        "name": "Yordan Letchkov",
        "goals": 2,
        "span": "1994"
      },
      {
        "name": "Asparuh Nikodimov",
        "goals": 1,
        "span": "1970"
      }
    ],
    "rivalries": [
      {
        "code": "ARG",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "HUN",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "SWE",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "ITA",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      }
    ]
  },
  "CAN": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 6,
      "gf": 2,
      "ga": 12,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Alphonso Davies",
        "goals": 1,
        "span": "2022"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "HUN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "URS",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "BEL",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "CHI": {
    "record": {
      "w": 11,
      "d": 7,
      "l": 15,
      "gf": 40,
      "ga": 49,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Leonel Sánchez",
        "goals": 4,
        "span": "1962"
      },
      {
        "name": "Marcelo Salas",
        "goals": 4,
        "span": "1998"
      },
      {
        "name": "Alexis Sánchez",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Atilio Cremaschi",
        "goals": 2,
        "span": "1950"
      },
      {
        "name": "Carlos Vidal",
        "goals": 2,
        "span": "1930"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 4,
        "w": 0,
        "d": 1,
        "l": 3
      },
      {
        "code": "ESP",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "ITA",
        "played": 3,
        "w": 1,
        "d": 1,
        "l": 1
      },
      {
        "code": "FRG",
        "played": 3,
        "w": 0,
        "d": 0,
        "l": 3
      }
    ]
  },
  "CIV": {
    "record": {
      "w": 3,
      "d": 1,
      "l": 5,
      "gf": 13,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Aruna Dindane",
        "goals": 2,
        "span": "2006"
      },
      {
        "name": "Didier Drogba",
        "goals": 2,
        "span": "2006–2010"
      },
      {
        "name": "Gervinho",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Wilfried Bony",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Bakari Koné",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "PRK",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "JPN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "NED",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "CMR": {
    "record": {
      "w": 5,
      "d": 8,
      "l": 13,
      "gf": 22,
      "ga": 47,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Roger Milla",
        "goals": 5,
        "span": "1990–1994"
      },
      {
        "name": "Samuel Eto'o",
        "goals": 3,
        "span": "2002–2010"
      },
      {
        "name": "François Omam-Biyik",
        "goals": 2,
        "span": "1990–1994"
      },
      {
        "name": "Patrick M'Boma",
        "goals": 2,
        "span": "1998–2002"
      },
      {
        "name": "Vincent Aboubakar",
        "goals": 2,
        "span": "2022"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "ITA",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ROU",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "COL": {
    "record": {
      "w": 9,
      "d": 3,
      "l": 10,
      "gf": 32,
      "ga": 30,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "James Rodríguez",
        "goals": 6,
        "span": "2014"
      },
      {
        "name": "Yerry Mina",
        "goals": 3,
        "span": "2018"
      },
      {
        "name": "Adolfo Valencia",
        "goals": 2,
        "span": "1994"
      },
      {
        "name": "Bernardo Redín",
        "goals": 2,
        "span": "1990"
      },
      {
        "name": "Jackson Martínez",
        "goals": 2,
        "span": "2014"
      }
    ],
    "rivalries": [
      {
        "code": "URU",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "JPN",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "YUG",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "ROU",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      }
    ]
  },
  "CRC": {
    "record": {
      "w": 6,
      "d": 5,
      "l": 10,
      "gf": 22,
      "ga": 39,
      "pensWon": 1,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Paulo Wanchope",
        "goals": 3,
        "span": "2002–2006"
      },
      {
        "name": "Rónald Gómez",
        "goals": 3,
        "span": "2002–2006"
      },
      {
        "name": "Bryan Ruiz",
        "goals": 2,
        "span": "2014"
      },
      {
        "name": "Hernán Medford",
        "goals": 1,
        "span": "1990"
      },
      {
        "name": "Joel Campbell",
        "goals": 1,
        "span": "2014"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 3,
        "w": 0,
        "d": 0,
        "l": 3
      },
      {
        "code": "GER",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "SCO",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "CRO": {
    "record": {
      "w": 13,
      "d": 8,
      "l": 9,
      "gf": 43,
      "ga": 33,
      "pensWon": 4,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Davor Šuker",
        "goals": 6,
        "span": "1998"
      },
      {
        "name": "Ivan Perišić",
        "goals": 6,
        "span": "2014–2022"
      },
      {
        "name": "Mario Mandžukić",
        "goals": 5,
        "span": "2014–2018"
      },
      {
        "name": "Andrej Kramarić",
        "goals": 3,
        "span": "2018–2022"
      },
      {
        "name": "Ivica Olić",
        "goals": 2,
        "span": "2002–2014"
      }
    ],
    "rivalries": [
      {
        "code": "JPN",
        "played": 3,
        "w": 1,
        "d": 2,
        "l": 0
      },
      {
        "code": "ARG",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "BRA",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "MAR",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      }
    ]
  },
  "CUB": {
    "record": {
      "w": 1,
      "d": 1,
      "l": 1,
      "gf": 5,
      "ga": 12,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Héctor Socorro",
        "goals": 3,
        "span": "1938"
      },
      {
        "name": "José Magriñá",
        "goals": 1,
        "span": "1938"
      },
      {
        "name": "Tomás Fernández",
        "goals": 1,
        "span": "1938"
      }
    ],
    "rivalries": [
      {
        "code": "ROU",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "CZE": {
    "record": {
      "w": 1,
      "d": 0,
      "l": 2,
      "gf": 3,
      "ga": 4,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Tomáš Rosický",
        "goals": 2,
        "span": "2006"
      },
      {
        "name": "Jan Koller",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "USA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "GHA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "ITA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "DEN": {
    "record": {
      "w": 9,
      "d": 6,
      "l": 8,
      "gf": 31,
      "ga": 29,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Jon Dahl Tomasson",
        "goals": 5,
        "span": "2002–2010"
      },
      {
        "name": "Preben Elkjær",
        "goals": 4,
        "span": "1986"
      },
      {
        "name": "Jesper Olsen",
        "goals": 3,
        "span": "1986"
      },
      {
        "name": "Brian Laudrup",
        "goals": 2,
        "span": "1998"
      },
      {
        "name": "Dennis Rommedahl",
        "goals": 2,
        "span": "2002–2010"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 4,
        "w": 1,
        "d": 1,
        "l": 2
      },
      {
        "code": "URU",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "AUS",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "SCO",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "ECU": {
    "record": {
      "w": 5,
      "d": 2,
      "l": 6,
      "gf": 14,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Enner Valencia",
        "goals": 6,
        "span": "2014–2022"
      },
      {
        "name": "Agustín Delgado",
        "goals": 3,
        "span": "2002–2006"
      },
      {
        "name": "Carlos Tenorio",
        "goals": 2,
        "span": "2006"
      },
      {
        "name": "Édison Méndez",
        "goals": 1,
        "span": "2002"
      },
      {
        "name": "Iván Kaviedes",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "CRO",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "POL",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "CRC",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "HON",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "EGY": {
    "record": {
      "w": 0,
      "d": 2,
      "l": 5,
      "gf": 5,
      "ga": 12,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Abdulrahman Fawzi",
        "goals": 2,
        "span": "1934"
      },
      {
        "name": "Mohamed Salah",
        "goals": 2,
        "span": "2018"
      },
      {
        "name": "Magdi Abdelghani",
        "goals": 1,
        "span": "1990"
      }
    ],
    "rivalries": [
      {
        "code": "HUN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "NED",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "IRL",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "ENG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "ENG": {
    "record": {
      "w": 32,
      "d": 22,
      "l": 20,
      "gf": 104,
      "ga": 68,
      "pensWon": 1,
      "pensLost": 3
    },
    "topScorers": [
      {
        "name": "Gary Lineker",
        "goals": 10,
        "span": "1986–1990"
      },
      {
        "name": "Harry Kane",
        "goals": 8,
        "span": "2018–2022"
      },
      {
        "name": "Geoff Hurst",
        "goals": 5,
        "span": "1966–1970"
      },
      {
        "name": "Bobby Charlton",
        "goals": 4,
        "span": "1962–1966"
      },
      {
        "name": "Michael Owen",
        "goals": 4,
        "span": "1998–2002"
      }
    ],
    "rivalries": [
      {
        "code": "ARG",
        "played": 5,
        "w": 3,
        "d": 1,
        "l": 1
      },
      {
        "code": "BEL",
        "played": 4,
        "w": 1,
        "d": 1,
        "l": 2
      },
      {
        "code": "FRG",
        "played": 4,
        "w": 1,
        "d": 2,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 4,
        "w": 0,
        "d": 1,
        "l": 3
      }
    ]
  },
  "ESP": {
    "record": {
      "w": 31,
      "d": 17,
      "l": 19,
      "gf": 108,
      "ga": 75,
      "pensWon": 1,
      "pensLost": 4
    },
    "topScorers": [
      {
        "name": "David Villa",
        "goals": 9,
        "span": "2006–2014"
      },
      {
        "name": "Emilio Butragueño",
        "goals": 5,
        "span": "1986"
      },
      {
        "name": "Fernando Hierro",
        "goals": 5,
        "span": "1994–2002"
      },
      {
        "name": "Fernando Morientes",
        "goals": 5,
        "span": "1998–2002"
      },
      {
        "name": "Raúl",
        "goals": 5,
        "span": "1998–2006"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 5,
        "w": 1,
        "d": 1,
        "l": 3
      },
      {
        "code": "CHI",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "SUI",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "PAR",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      }
    ]
  },
  "FRA": {
    "record": {
      "w": 39,
      "d": 14,
      "l": 20,
      "gf": 136,
      "ga": 85,
      "pensWon": 2,
      "pensLost": 3
    },
    "topScorers": [
      {
        "name": "Just Fontaine",
        "goals": 13,
        "span": "1958"
      },
      {
        "name": "Kylian Mbappé",
        "goals": 12,
        "span": "2018–2022"
      },
      {
        "name": "Thierry Henry",
        "goals": 6,
        "span": "1998–2006"
      },
      {
        "name": "Michel Platini",
        "goals": 5,
        "span": "1978–1986"
      },
      {
        "name": "Olivier Giroud",
        "goals": 5,
        "span": "2014–2022"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 5,
        "w": 1,
        "d": 2,
        "l": 2
      },
      {
        "code": "MEX",
        "played": 4,
        "w": 2,
        "d": 1,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 4,
        "w": 2,
        "d": 1,
        "l": 1
      },
      {
        "code": "DEN",
        "played": 4,
        "w": 2,
        "d": 1,
        "l": 1
      }
    ]
  },
  "FRG": {
    "record": {
      "w": 36,
      "d": 14,
      "l": 12,
      "gf": 131,
      "ga": 77,
      "pensWon": 3,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Gerd Müller",
        "goals": 14,
        "span": "1970–1974"
      },
      {
        "name": "Helmut Rahn",
        "goals": 10,
        "span": "1954–1958"
      },
      {
        "name": "Karl-Heinz Rummenigge",
        "goals": 9,
        "span": "1978–1986"
      },
      {
        "name": "Uwe Seeler",
        "goals": 9,
        "span": "1958–1970"
      },
      {
        "name": "Hans Schäfer",
        "goals": 7,
        "span": "1954–1958"
      }
    ],
    "rivalries": [
      {
        "code": "YUG",
        "played": 5,
        "w": 4,
        "d": 0,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 4,
        "w": 2,
        "d": 1,
        "l": 1
      },
      {
        "code": "ENG",
        "played": 4,
        "w": 1,
        "d": 2,
        "l": 1
      },
      {
        "code": "ITA",
        "played": 4,
        "w": 0,
        "d": 2,
        "l": 2
      }
    ]
  },
  "GDR": {
    "record": {
      "w": 2,
      "d": 2,
      "l": 2,
      "gf": 5,
      "ga": 5,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Joachim Streich",
        "goals": 2,
        "span": "1974"
      },
      {
        "name": "Jürgen Sparwasser",
        "goals": 1,
        "span": "1974"
      },
      {
        "name": "Martin Hoffmann",
        "goals": 1,
        "span": "1974"
      }
    ],
    "rivalries": [
      {
        "code": "AUS",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "FRG",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "CHI",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "GER": {
    "record": {
      "w": 32,
      "d": 7,
      "l": 11,
      "gf": 101,
      "ga": 53,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Miroslav Klose",
        "goals": 16,
        "span": "2002–2014"
      },
      {
        "name": "Thomas Müller",
        "goals": 10,
        "span": "2010–2014"
      },
      {
        "name": "Jürgen Klinsmann",
        "goals": 8,
        "span": "1994–1998"
      },
      {
        "name": "Lukas Podolski",
        "goals": 5,
        "span": "2006–2010"
      },
      {
        "name": "Edmund Conen",
        "goals": 4,
        "span": "1934"
      }
    ],
    "rivalries": [
      {
        "code": "SWE",
        "played": 3,
        "w": 3,
        "d": 0,
        "l": 0
      },
      {
        "code": "USA",
        "played": 3,
        "w": 3,
        "d": 0,
        "l": 0
      },
      {
        "code": "KOR",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      }
    ]
  },
  "GHA": {
    "record": {
      "w": 5,
      "d": 3,
      "l": 7,
      "gf": 18,
      "ga": 23,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Asamoah Gyan",
        "goals": 6,
        "span": "2006–2014"
      },
      {
        "name": "André Ayew",
        "goals": 3,
        "span": "2014–2022"
      },
      {
        "name": "Mohammed Kudus",
        "goals": 2,
        "span": "2022"
      },
      {
        "name": "Sulley Muntari",
        "goals": 2,
        "span": "2006–2010"
      },
      {
        "name": "Haminu Draman",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "USA",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "GER",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "URU",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "POR",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      }
    ]
  },
  "GRE": {
    "record": {
      "w": 2,
      "d": 2,
      "l": 6,
      "gf": 5,
      "ga": 20,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Andreas Samaris",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Dimitris Salpingidis",
        "goals": 1,
        "span": "2010"
      },
      {
        "name": "Georgios Samaras",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Sokratis Papastathopoulos",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Vasilis Torosidis",
        "goals": 1,
        "span": "2010"
      }
    ],
    "rivalries": [
      {
        "code": "NGA",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "CIV",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "BUL",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "HAI": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 3,
      "gf": 2,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Emmanuel Sanon",
        "goals": 2,
        "span": "1974"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "POL",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "HON": {
    "record": {
      "w": 0,
      "d": 3,
      "l": 6,
      "gf": 3,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Antonio Laing",
        "goals": 1,
        "span": "1982"
      },
      {
        "name": "Carlo Costly",
        "goals": 1,
        "span": "2014"
      },
      {
        "name": "Héctor Zelaya",
        "goals": 1,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "ESP",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "SUI",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "NIR",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "YUG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "HUN": {
    "record": {
      "w": 15,
      "d": 3,
      "l": 14,
      "gf": 87,
      "ga": 57,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Sándor Kocsis",
        "goals": 11,
        "span": "1954"
      },
      {
        "name": "Lajos Tichy",
        "goals": 7,
        "span": "1958–1962"
      },
      {
        "name": "György Sárosi",
        "goals": 6,
        "span": "1934–1938"
      },
      {
        "name": "Gyula Zsengellér",
        "goals": 5,
        "span": "1938"
      },
      {
        "name": "Ferenc Bene",
        "goals": 4,
        "span": "1966"
      }
    ],
    "rivalries": [
      {
        "code": "ARG",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "BRA",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "BUL",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      }
    ]
  },
  "IDN": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 1,
      "gf": 0,
      "ga": 6,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [],
    "rivalries": [
      {
        "code": "HUN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "IRL": {
    "record": {
      "w": 2,
      "d": 8,
      "l": 3,
      "gf": 10,
      "ga": 10,
      "pensWon": 1,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Robbie Keane",
        "goals": 3,
        "span": "2002"
      },
      {
        "name": "Damien Duff",
        "goals": 1,
        "span": "2002"
      },
      {
        "name": "Gary Breen",
        "goals": 1,
        "span": "2002"
      },
      {
        "name": "John Aldridge",
        "goals": 1,
        "span": "1994"
      },
      {
        "name": "Kevin Sheedy",
        "goals": 1,
        "span": "1990"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "NED",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "KSA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ENG",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "IRN": {
    "record": {
      "w": 3,
      "d": 4,
      "l": 11,
      "gf": 13,
      "ga": 31,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Mehdi Taremi",
        "goals": 2,
        "span": "2022"
      },
      {
        "name": "Hamid Estili",
        "goals": 1,
        "span": "1998"
      },
      {
        "name": "Hassan Roshan",
        "goals": 1,
        "span": "1978"
      },
      {
        "name": "Iraj Danaeifard",
        "goals": 1,
        "span": "1978"
      },
      {
        "name": "Karim Ansarifard",
        "goals": 1,
        "span": "2018"
      }
    ],
    "rivalries": [
      {
        "code": "USA",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "POR",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "MAR",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "WAL",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "IRQ": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 3,
      "gf": 1,
      "ga": 4,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Ahmed Radhi",
        "goals": 1,
        "span": "1986"
      }
    ],
    "rivalries": [
      {
        "code": "PAR",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "BEL",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "MEX",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "ITA": {
    "record": {
      "w": 45,
      "d": 21,
      "l": 17,
      "gf": 128,
      "ga": 77,
      "pensWon": 1,
      "pensLost": 3
    },
    "topScorers": [
      {
        "name": "Christian Vieri",
        "goals": 9,
        "span": "1998–2002"
      },
      {
        "name": "Paolo Rossi",
        "goals": 9,
        "span": "1978–1982"
      },
      {
        "name": "Roberto Baggio",
        "goals": 9,
        "span": "1990–1998"
      },
      {
        "name": "Salvatore Schillaci",
        "goals": 6,
        "span": "1990"
      },
      {
        "name": "Alessandro Altobelli",
        "goals": 5,
        "span": "1982–1986"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 5,
        "w": 2,
        "d": 2,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 5,
        "w": 2,
        "d": 1,
        "l": 2
      },
      {
        "code": "ARG",
        "played": 5,
        "w": 2,
        "d": 3,
        "l": 0
      },
      {
        "code": "AUT",
        "played": 4,
        "w": 4,
        "d": 0,
        "l": 0
      }
    ]
  },
  "JPN": {
    "record": {
      "w": 7,
      "d": 6,
      "l": 12,
      "gf": 25,
      "ga": 33,
      "pensWon": 0,
      "pensLost": 2
    },
    "topScorers": [
      {
        "name": "Keisuke Honda",
        "goals": 4,
        "span": "2010–2018"
      },
      {
        "name": "Junichi Inamoto",
        "goals": 2,
        "span": "2002"
      },
      {
        "name": "Ritsu Dōan",
        "goals": 2,
        "span": "2022"
      },
      {
        "name": "Shinji Okazaki",
        "goals": 2,
        "span": "2010–2014"
      },
      {
        "name": "Takashi Inui",
        "goals": 2,
        "span": "2018"
      }
    ],
    "rivalries": [
      {
        "code": "CRO",
        "played": 3,
        "w": 0,
        "d": 2,
        "l": 1
      },
      {
        "code": "COL",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "BEL",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "RUS",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "KOR": {
    "record": {
      "w": 7,
      "d": 10,
      "l": 21,
      "gf": 39,
      "ga": 78,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Heung-min Son",
        "goals": 3,
        "span": "2014–2018"
      },
      {
        "name": "Ji-sung Park",
        "goals": 3,
        "span": "2002–2010"
      },
      {
        "name": "Jung-hwan Ahn",
        "goals": 3,
        "span": "2002–2006"
      },
      {
        "name": "Cho Gue-sung",
        "goals": 2,
        "span": "2022"
      },
      {
        "name": "Chung-yong Lee",
        "goals": 2,
        "span": "2010"
      }
    ],
    "rivalries": [
      {
        "code": "GER",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "BEL",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "ESP",
        "played": 3,
        "w": 0,
        "d": 2,
        "l": 1
      },
      {
        "code": "URU",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      }
    ]
  },
  "KSA": {
    "record": {
      "w": 4,
      "d": 2,
      "l": 13,
      "gf": 14,
      "ga": 44,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Salem Al-Dawsari",
        "goals": 3,
        "span": "2018–2022"
      },
      {
        "name": "Sami Al-Jaber",
        "goals": 3,
        "span": "1994–2006"
      },
      {
        "name": "Fuad Anwar",
        "goals": 2,
        "span": "1994"
      },
      {
        "name": "Fahad Al-Ghesheyan",
        "goals": 1,
        "span": "1994"
      },
      {
        "name": "Saeed Al-Owairan",
        "goals": 1,
        "span": "1994"
      }
    ],
    "rivalries": [
      {
        "code": "MAR",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "BEL",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "EGY",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "KUW": {
    "record": {
      "w": 0,
      "d": 1,
      "l": 2,
      "gf": 2,
      "ga": 6,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Abdullah Al-Buloushi",
        "goals": 1,
        "span": "1982"
      },
      {
        "name": "Faisal Al-Dakhil",
        "goals": 1,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "TCH",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "FRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "ENG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "MAR": {
    "record": {
      "w": 5,
      "d": 7,
      "l": 11,
      "gf": 20,
      "ga": 27,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Youssef En-Nesyri",
        "goals": 3,
        "span": "2018–2022"
      },
      {
        "name": "Abdeljalil Hadda",
        "goals": 2,
        "span": "1998"
      },
      {
        "name": "Abderrazak Khairi",
        "goals": 2,
        "span": "1986"
      },
      {
        "name": "Salaheddine Bassir",
        "goals": 2,
        "span": "1998"
      },
      {
        "name": "Abdelkrim Merry",
        "goals": 1,
        "span": "1986"
      }
    ],
    "rivalries": [
      {
        "code": "POR",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "BEL",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "FRG",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "ESP",
        "played": 2,
        "w": 0,
        "d": 2,
        "l": 0
      }
    ]
  },
  "MEX": {
    "record": {
      "w": 17,
      "d": 15,
      "l": 28,
      "gf": 62,
      "ga": 101,
      "pensWon": 0,
      "pensLost": 2
    },
    "topScorers": [
      {
        "name": "Javier Hernández",
        "goals": 4,
        "span": "2010–2018"
      },
      {
        "name": "Luis Hernández",
        "goals": 4,
        "span": "1998"
      },
      {
        "name": "Cuauhtémoc Blanco",
        "goals": 3,
        "span": "1998–2010"
      },
      {
        "name": "Rafael Márquez",
        "goals": 3,
        "span": "2006–2014"
      },
      {
        "name": "Alberto García Aspe",
        "goals": 2,
        "span": "1994–1998"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 5,
        "w": 0,
        "d": 1,
        "l": 4
      },
      {
        "code": "FRA",
        "played": 4,
        "w": 1,
        "d": 1,
        "l": 2
      },
      {
        "code": "ARG",
        "played": 4,
        "w": 0,
        "d": 0,
        "l": 4
      },
      {
        "code": "BEL",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      }
    ]
  },
  "NED": {
    "record": {
      "w": 30,
      "d": 14,
      "l": 11,
      "gf": 96,
      "ga": 52,
      "pensWon": 1,
      "pensLost": 3
    },
    "topScorers": [
      {
        "name": "Johnny Rep",
        "goals": 7,
        "span": "1974–1978"
      },
      {
        "name": "Arjen Robben",
        "goals": 6,
        "span": "2006–2014"
      },
      {
        "name": "Dennis Bergkamp",
        "goals": 6,
        "span": "1994–1998"
      },
      {
        "name": "Rob Rensenbrink",
        "goals": 6,
        "span": "1974–1978"
      },
      {
        "name": "Robin van Persie",
        "goals": 6,
        "span": "2006–2014"
      }
    ],
    "rivalries": [
      {
        "code": "ARG",
        "played": 6,
        "w": 2,
        "d": 3,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 5,
        "w": 3,
        "d": 1,
        "l": 1
      },
      {
        "code": "FRG",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "URU",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      }
    ]
  },
  "NGA": {
    "record": {
      "w": 6,
      "d": 3,
      "l": 12,
      "gf": 23,
      "ga": 30,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Ahmed Musa",
        "goals": 4,
        "span": "2014–2018"
      },
      {
        "name": "Daniel Amokachi",
        "goals": 2,
        "span": "1994"
      },
      {
        "name": "Emmanuel Amunike",
        "goals": 2,
        "span": "1994"
      },
      {
        "name": "Kalu Uche",
        "goals": 2,
        "span": "2010"
      },
      {
        "name": "Finidi George",
        "goals": 1,
        "span": "1994"
      }
    ],
    "rivalries": [
      {
        "code": "ARG",
        "played": 5,
        "w": 0,
        "d": 0,
        "l": 5
      },
      {
        "code": "BUL",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "GRE",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "ESP",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "NIR": {
    "record": {
      "w": 3,
      "d": 5,
      "l": 5,
      "gf": 13,
      "ga": 23,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Peter McParland",
        "goals": 5,
        "span": "1958"
      },
      {
        "name": "Gerry Armstrong",
        "goals": 3,
        "span": "1982"
      },
      {
        "name": "Billy Hamilton",
        "goals": 2,
        "span": "1982"
      },
      {
        "name": "Colin Clarke",
        "goals": 1,
        "span": "1986"
      },
      {
        "name": "Norman Whiteside",
        "goals": 1,
        "span": "1986"
      }
    ],
    "rivalries": [
      {
        "code": "TCH",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "ESP",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "FRA",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "ARG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "NOR": {
    "record": {
      "w": 2,
      "d": 3,
      "l": 3,
      "gf": 7,
      "ga": 8,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Kjetil Rekdal",
        "goals": 2,
        "span": "1994–1998"
      },
      {
        "name": "Arne Brustad",
        "goals": 1,
        "span": "1938"
      },
      {
        "name": "Dan Eggen",
        "goals": 1,
        "span": "1998"
      },
      {
        "name": "Håvard Flo",
        "goals": 1,
        "span": "1998"
      },
      {
        "name": "Tore André Flo",
        "goals": 1,
        "span": "1998"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 3,
        "w": 0,
        "d": 0,
        "l": 3
      },
      {
        "code": "MEX",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "IRL",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "NZL": {
    "record": {
      "w": 0,
      "d": 3,
      "l": 3,
      "gf": 4,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Shane Smeltz",
        "goals": 1,
        "span": "2010"
      },
      {
        "name": "Steve Sumner",
        "goals": 1,
        "span": "1982"
      },
      {
        "name": "Steve Wooddin",
        "goals": 1,
        "span": "1982"
      },
      {
        "name": "Winston Reid",
        "goals": 1,
        "span": "2010"
      }
    ],
    "rivalries": [
      {
        "code": "SCO",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "URS",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "SVK",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "PAN": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 3,
      "gf": 2,
      "ga": 11,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Felipe Baloy",
        "goals": 1,
        "span": "2018"
      }
    ],
    "rivalries": [
      {
        "code": "BEL",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "ENG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "TUN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "PAR": {
    "record": {
      "w": 7,
      "d": 10,
      "l": 10,
      "gf": 30,
      "ga": 38,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Nelson Cuevas",
        "goals": 3,
        "span": "2002–2006"
      },
      {
        "name": "Florencio Amarilla",
        "goals": 2,
        "span": "1958"
      },
      {
        "name": "Jorge Lino Romero",
        "goals": 2,
        "span": "1958"
      },
      {
        "name": "José Parodi",
        "goals": 2,
        "span": "1958"
      },
      {
        "name": "Juan Bautista Agüero",
        "goals": 2,
        "span": "1958"
      }
    ],
    "rivalries": [
      {
        "code": "ESP",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "BEL",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "ITA",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      }
    ]
  },
  "PER": {
    "record": {
      "w": 5,
      "d": 3,
      "l": 10,
      "gf": 21,
      "ga": 33,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Teófilo Cubillas",
        "goals": 10,
        "span": "1970–1978"
      },
      {
        "name": "Alberto Gallardo",
        "goals": 2,
        "span": "1970"
      },
      {
        "name": "André Carrillo",
        "goals": 1,
        "span": "2018"
      },
      {
        "name": "César Cueto",
        "goals": 1,
        "span": "1978"
      },
      {
        "name": "Guillermo La Rosa",
        "goals": 1,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "POL",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "BUL",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "MAR",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "POL": {
    "record": {
      "w": 17,
      "d": 6,
      "l": 15,
      "gf": 49,
      "ga": 50,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Grzegorz Lato",
        "goals": 10,
        "span": "1974–1982"
      },
      {
        "name": "Andrzej Szarmach",
        "goals": 7,
        "span": "1974–1982"
      },
      {
        "name": "Zbigniew Boniek",
        "goals": 6,
        "span": "1978–1982"
      },
      {
        "name": "Ernst Wilimowski",
        "goals": 4,
        "span": "1938"
      },
      {
        "name": "Kazimierz Deyna",
        "goals": 4,
        "span": "1974–1978"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 4,
        "w": 1,
        "d": 0,
        "l": 3
      },
      {
        "code": "ARG",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "ITA",
        "played": 3,
        "w": 1,
        "d": 1,
        "l": 1
      },
      {
        "code": "PER",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      }
    ]
  },
  "POR": {
    "record": {
      "w": 17,
      "d": 6,
      "l": 12,
      "gf": 61,
      "ga": 41,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Eusébio",
        "goals": 9,
        "span": "1966"
      },
      {
        "name": "Cristiano Ronaldo",
        "goals": 8,
        "span": "2006–2022"
      },
      {
        "name": "Pauleta",
        "goals": 4,
        "span": "2002–2006"
      },
      {
        "name": "Gonçalo Ramos",
        "goals": 3,
        "span": "2022"
      },
      {
        "name": "José Augusto",
        "goals": 3,
        "span": "1966"
      }
    ],
    "rivalries": [
      {
        "code": "ENG",
        "played": 3,
        "w": 1,
        "d": 1,
        "l": 1
      },
      {
        "code": "MAR",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "PRK",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "GHA",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      }
    ]
  },
  "PRK": {
    "record": {
      "w": 1,
      "d": 1,
      "l": 5,
      "gf": 6,
      "ga": 21,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Seung-zin Pak",
        "goals": 2,
        "span": "1966"
      },
      {
        "name": "Dong-woon Li",
        "goals": 1,
        "span": "1966"
      },
      {
        "name": "Doo-ik Pak",
        "goals": 1,
        "span": "1966"
      },
      {
        "name": "Seung-kook Yang",
        "goals": 1,
        "span": "1966"
      },
      {
        "name": "Yun-nam Ji",
        "goals": 1,
        "span": "2010"
      }
    ],
    "rivalries": [
      {
        "code": "POR",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "ITA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "URS",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "CHI",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "QAT": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 3,
      "gf": 1,
      "ga": 7,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Mohammed Muntari",
        "goals": 1,
        "span": "2022"
      }
    ],
    "rivalries": [
      {
        "code": "ECU",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "SEN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "NED",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "ROU": {
    "record": {
      "w": 8,
      "d": 5,
      "l": 8,
      "gf": 30,
      "ga": 32,
      "pensWon": 0,
      "pensLost": 2
    },
    "topScorers": [
      {
        "name": "Florin Răducioiu",
        "goals": 4,
        "span": "1994"
      },
      {
        "name": "Gheorghe Hagi",
        "goals": 3,
        "span": "1994"
      },
      {
        "name": "Ștefan Dobay",
        "goals": 3,
        "span": "1934–1938"
      },
      {
        "name": "Dan Petrescu",
        "goals": 2,
        "span": "1994–1998"
      },
      {
        "name": "Florea Dumitrache",
        "goals": 2,
        "span": "1970"
      }
    ],
    "rivalries": [
      {
        "code": "COL",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "TCH",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "ENG",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "ARG",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      }
    ]
  },
  "RSA": {
    "record": {
      "w": 2,
      "d": 4,
      "l": 3,
      "gf": 11,
      "ga": 16,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Benni McCarthy",
        "goals": 2,
        "span": "1998–2002"
      },
      {
        "name": "Shaun Bartlett",
        "goals": 2,
        "span": "1998"
      },
      {
        "name": "Bongani Khumalo",
        "goals": 1,
        "span": "2010"
      },
      {
        "name": "Katlego Mphela",
        "goals": 1,
        "span": "2010"
      },
      {
        "name": "Lucas Radebe",
        "goals": 1,
        "span": "2002"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "DEN",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "KSA",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "PAR",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "RUS": {
    "record": {
      "w": 4,
      "d": 4,
      "l": 6,
      "gf": 24,
      "ga": 20,
      "pensWon": 1,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Oleg Salenko",
        "goals": 6,
        "span": "1994"
      },
      {
        "name": "Denis Cheryshev",
        "goals": 4,
        "span": "2018"
      },
      {
        "name": "Artem Dzyuba",
        "goals": 3,
        "span": "2018"
      },
      {
        "name": "Aleksandr Golovin",
        "goals": 1,
        "span": "2018"
      },
      {
        "name": "Aleksandr Kerzhakov",
        "goals": 1,
        "span": "2014"
      }
    ],
    "rivalries": [
      {
        "code": "BEL",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "CMR",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "TUN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "KSA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "SCO": {
    "record": {
      "w": 4,
      "d": 7,
      "l": 12,
      "gf": 25,
      "ga": 41,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Joe Jordan",
        "goals": 4,
        "span": "1974–1982"
      },
      {
        "name": "Archie Gemmill",
        "goals": 2,
        "span": "1978"
      },
      {
        "name": "John Wark",
        "goals": 2,
        "span": "1982"
      },
      {
        "name": "Kenny Dalglish",
        "goals": 2,
        "span": "1978–1982"
      },
      {
        "name": "Bobby Collins",
        "goals": 1,
        "span": "1958"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 4,
        "w": 0,
        "d": 1,
        "l": 3
      },
      {
        "code": "URU",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "YUG",
        "played": 2,
        "w": 0,
        "d": 2,
        "l": 0
      },
      {
        "code": "ZAI",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "SEN": {
    "record": {
      "w": 5,
      "d": 3,
      "l": 4,
      "gf": 16,
      "ga": 17,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Papa Bouba Diop",
        "goals": 3,
        "span": "2002"
      },
      {
        "name": "Henri Camara",
        "goals": 2,
        "span": "2002"
      },
      {
        "name": "Bamba Dieng",
        "goals": 1,
        "span": "2022"
      },
      {
        "name": "Boulaye Dia",
        "goals": 1,
        "span": "2022"
      },
      {
        "name": "Famara Diédhiou",
        "goals": 1,
        "span": "2022"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "POL",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "QAT",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "SLV": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 6,
      "gf": 1,
      "ga": 22,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Luis Ramírez Zapata",
        "goals": 1,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "BEL",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "MEX",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "URS",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "HUN",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "SUI": {
    "record": {
      "w": 14,
      "d": 8,
      "l": 19,
      "gf": 55,
      "ga": 73,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Josef Hügi",
        "goals": 6,
        "span": "1954"
      },
      {
        "name": "Xherdan Shaqiri",
        "goals": 5,
        "span": "2014–2022"
      },
      {
        "name": "André Abegglen",
        "goals": 4,
        "span": "1934–1938"
      },
      {
        "name": "Robert Ballaman",
        "goals": 4,
        "span": "1954"
      },
      {
        "name": "Jacques Fatton",
        "goals": 3,
        "span": "1950–1954"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "ESP",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "BRA",
        "played": 3,
        "w": 0,
        "d": 2,
        "l": 1
      },
      {
        "code": "GER",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      }
    ]
  },
  "SVK": {
    "record": {
      "w": 1,
      "d": 1,
      "l": 2,
      "gf": 5,
      "ga": 7,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Róbert Vittek",
        "goals": 4,
        "span": "2010"
      },
      {
        "name": "Kamil Kopúnek",
        "goals": 1,
        "span": "2010"
      }
    ],
    "rivalries": [
      {
        "code": "ITA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "NZL",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "PAR",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "NED",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "SWE": {
    "record": {
      "w": 19,
      "d": 13,
      "l": 19,
      "gf": 80,
      "ga": 73,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Henrik Larsson",
        "goals": 5,
        "span": "1994–2006"
      },
      {
        "name": "Kennet Andersson",
        "goals": 5,
        "span": "1994"
      },
      {
        "name": "Agne Simonsson",
        "goals": 4,
        "span": "1958"
      },
      {
        "name": "Kurt Hamrin",
        "goals": 4,
        "span": "1958"
      },
      {
        "name": "Martin Dahlin",
        "goals": 4,
        "span": "1994"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 7,
        "w": 0,
        "d": 2,
        "l": 5
      },
      {
        "code": "URU",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "GER",
        "played": 3,
        "w": 0,
        "d": 0,
        "l": 3
      },
      {
        "code": "ENG",
        "played": 3,
        "w": 0,
        "d": 2,
        "l": 1
      }
    ]
  },
  "TCH": {
    "record": {
      "w": 11,
      "d": 5,
      "l": 14,
      "gf": 44,
      "ga": 45,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Oldřich Nejedlý",
        "goals": 7,
        "span": "1934–1938"
      },
      {
        "name": "Tomáš Skuhravý",
        "goals": 5,
        "span": "1990"
      },
      {
        "name": "Zdeněk Zikán",
        "goals": 4,
        "span": "1958"
      },
      {
        "name": "Adolf Scherer",
        "goals": 3,
        "span": "1962"
      },
      {
        "name": "Antonín Panenka",
        "goals": 2,
        "span": "1982"
      }
    ],
    "rivalries": [
      {
        "code": "BRA",
        "played": 5,
        "w": 0,
        "d": 2,
        "l": 3
      },
      {
        "code": "ROU",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "AUT",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      },
      {
        "code": "ITA",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      }
    ]
  },
  "TUN": {
    "record": {
      "w": 3,
      "d": 5,
      "l": 10,
      "gf": 14,
      "ga": 26,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Wahbi Khazri",
        "goals": 3,
        "span": "2018–2022"
      },
      {
        "name": "Ali Kaabi",
        "goals": 1,
        "span": "1978"
      },
      {
        "name": "Dylan Bronn",
        "goals": 1,
        "span": "2018"
      },
      {
        "name": "Fakhreddine Ben Youssef",
        "goals": 1,
        "span": "2018"
      },
      {
        "name": "Ferjani Sassi",
        "goals": 1,
        "span": "2018"
      }
    ],
    "rivalries": [
      {
        "code": "ENG",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "BEL",
        "played": 2,
        "w": 0,
        "d": 1,
        "l": 1
      },
      {
        "code": "MEX",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "PAN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "TUR": {
    "record": {
      "w": 5,
      "d": 1,
      "l": 4,
      "gf": 20,
      "ga": 17,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Burhan Sargun",
        "goals": 3,
        "span": "1954"
      },
      {
        "name": "İlhan Mansız",
        "goals": 3,
        "span": "2002"
      },
      {
        "name": "Suat Mamat",
        "goals": 3,
        "span": "1954"
      },
      {
        "name": "Hasan Şaş",
        "goals": 2,
        "span": "2002"
      },
      {
        "name": "Lefter Küçükandonyadis",
        "goals": 2,
        "span": "1954"
      }
    ],
    "rivalries": [
      {
        "code": "KOR",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "FRG",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "BRA",
        "played": 2,
        "w": 0,
        "d": 0,
        "l": 2
      },
      {
        "code": "JPN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      }
    ]
  },
  "UKR": {
    "record": {
      "w": 2,
      "d": 1,
      "l": 2,
      "gf": 5,
      "ga": 7,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Andriy Shevchenko",
        "goals": 2,
        "span": "2006"
      },
      {
        "name": "Andriy Rusol",
        "goals": 1,
        "span": "2006"
      },
      {
        "name": "Maksym Kalynychenko",
        "goals": 1,
        "span": "2006"
      },
      {
        "name": "Serhii Rebrov",
        "goals": 1,
        "span": "2006"
      }
    ],
    "rivalries": [
      {
        "code": "KSA",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "TUN",
        "played": 1,
        "w": 1,
        "d": 0,
        "l": 0
      },
      {
        "code": "ESP",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "SUI",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      }
    ]
  },
  "URS": {
    "record": {
      "w": 15,
      "d": 6,
      "l": 10,
      "gf": 53,
      "ga": 34,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Valentin Ivanov",
        "goals": 5,
        "span": "1958–1962"
      },
      {
        "name": "Anatoliy Byshovets",
        "goals": 4,
        "span": "1970"
      },
      {
        "name": "Igor Chislenko",
        "goals": 4,
        "span": "1962–1966"
      },
      {
        "name": "Ihor Belanov",
        "goals": 4,
        "span": "1986"
      },
      {
        "name": "Valeriy Porkujan",
        "goals": 4,
        "span": "1966"
      }
    ],
    "rivalries": [
      {
        "code": "BEL",
        "played": 3,
        "w": 2,
        "d": 0,
        "l": 1
      },
      {
        "code": "HUN",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "ENG",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      },
      {
        "code": "URU",
        "played": 2,
        "w": 1,
        "d": 0,
        "l": 1
      }
    ]
  },
  "URU": {
    "record": {
      "w": 25,
      "d": 13,
      "l": 21,
      "gf": 89,
      "ga": 76,
      "pensWon": 1,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Oscar Míguez",
        "goals": 8,
        "span": "1950–1954"
      },
      {
        "name": "Luis Suárez",
        "goals": 7,
        "span": "2010–2018"
      },
      {
        "name": "Diego Forlán",
        "goals": 6,
        "span": "2002–2010"
      },
      {
        "name": "Edinson Cavani",
        "goals": 5,
        "span": "2010–2018"
      },
      {
        "name": "Juan Alberto Schiaffino",
        "goals": 5,
        "span": "1950–1954"
      }
    ],
    "rivalries": [
      {
        "code": "FRA",
        "played": 4,
        "w": 1,
        "d": 2,
        "l": 1
      },
      {
        "code": "ENG",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      },
      {
        "code": "KOR",
        "played": 3,
        "w": 2,
        "d": 1,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      }
    ]
  },
  "USA": {
    "record": {
      "w": 9,
      "d": 8,
      "l": 20,
      "gf": 40,
      "ga": 66,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Landon Donovan",
        "goals": 5,
        "span": "2002–2010"
      },
      {
        "name": "Bert Patenaude",
        "goals": 4,
        "span": "1930"
      },
      {
        "name": "Clint Dempsey",
        "goals": 4,
        "span": "2006–2014"
      },
      {
        "name": "Brian McBride",
        "goals": 3,
        "span": "1998–2002"
      },
      {
        "name": "Aldo Donelli",
        "goals": 1,
        "span": "1934"
      }
    ],
    "rivalries": [
      {
        "code": "ENG",
        "played": 3,
        "w": 1,
        "d": 2,
        "l": 0
      },
      {
        "code": "GHA",
        "played": 3,
        "w": 1,
        "d": 0,
        "l": 2
      },
      {
        "code": "ITA",
        "played": 3,
        "w": 0,
        "d": 1,
        "l": 2
      },
      {
        "code": "GER",
        "played": 3,
        "w": 0,
        "d": 0,
        "l": 3
      }
    ]
  },
  "WAL": {
    "record": {
      "w": 1,
      "d": 4,
      "l": 3,
      "gf": 5,
      "ga": 10,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [
      {
        "name": "Ivor Allchurch",
        "goals": 2,
        "span": "1958"
      },
      {
        "name": "Gareth Bale",
        "goals": 1,
        "span": "2022"
      },
      {
        "name": "John Charles",
        "goals": 1,
        "span": "1958"
      },
      {
        "name": "Terry Medwin",
        "goals": 1,
        "span": "1958"
      }
    ],
    "rivalries": [
      {
        "code": "HUN",
        "played": 2,
        "w": 1,
        "d": 1,
        "l": 0
      },
      {
        "code": "MEX",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "SWE",
        "played": 1,
        "w": 0,
        "d": 1,
        "l": 0
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  },
  "YUG": {
    "record": {
      "w": 16,
      "d": 8,
      "l": 13,
      "gf": 60,
      "ga": 46,
      "pensWon": 0,
      "pensLost": 1
    },
    "topScorers": [
      {
        "name": "Dražan Jerković",
        "goals": 4,
        "span": "1962"
      },
      {
        "name": "Dragan Stojković",
        "goals": 3,
        "span": "1990–1998"
      },
      {
        "name": "Dušan Bajević",
        "goals": 3,
        "span": "1974"
      },
      {
        "name": "Ivan Bek",
        "goals": 3,
        "span": "1930"
      },
      {
        "name": "Milan Galić",
        "goals": 3,
        "span": "1962"
      }
    ],
    "rivalries": [
      {
        "code": "FRG",
        "played": 5,
        "w": 1,
        "d": 0,
        "l": 4
      },
      {
        "code": "BRA",
        "played": 4,
        "w": 1,
        "d": 2,
        "l": 1
      },
      {
        "code": "FRA",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      },
      {
        "code": "COL",
        "played": 2,
        "w": 2,
        "d": 0,
        "l": 0
      }
    ]
  },
  "ZAI": {
    "record": {
      "w": 0,
      "d": 0,
      "l": 3,
      "gf": 0,
      "ga": 14,
      "pensWon": 0,
      "pensLost": 0
    },
    "topScorers": [],
    "rivalries": [
      {
        "code": "SCO",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "YUG",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      },
      {
        "code": "BRA",
        "played": 1,
        "w": 0,
        "d": 0,
        "l": 1
      }
    ]
  }
};
