import { Match, TournamentData } from "./types";

const M = (
  top: number,
  bot: number,
  w: number,
  p: string | null = null,
  x: string | null = null,
  g: [string[], string[]] | null = null
): Match => ({
  s: [top, bot],
  w,
  p: p || null,
  x: x || null,
  g: g || null,
});

export const TEAMS: Record<string, [string, string]> = {
  GER: ["Germany", "🇩🇪"],
  BRA: ["Brazil", "🇧🇷"],
  PAR: ["Paraguay", "🇵🇾"],
  USA: ["United States", "🇺🇸"],
  MEX: ["Mexico", "🇲🇽"],
  ESP: ["Spain", "🇪🇸"],
  IRL: ["Rep. Ireland", "🇮🇪"],
  KOR: ["South Korea", "🇰🇷"],
  ITA: ["Italy", "🇮🇹"],
  ENG: ["England", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"],
  DEN: ["Denmark", "🇩🇰"],
  BEL: ["Belgium", "🇧🇪"],
  SEN: ["Senegal", "🇸🇳"],
  SWE: ["Sweden", "🇸🇪"],
  TUR: ["Türkiye", "🇹🇷"],
  JPN: ["Japan", "🇯🇵"],
  ARG: ["Argentina", "🇦🇷"],
  ECU: ["Ecuador", "🇪🇨"],
  POR: ["Portugal", "🇵🇹"],
  NED: ["Netherlands", "🇳🇱"],
  AUS: ["Australia", "🇦🇺"],
  SUI: ["Switzerland", "🇨🇭"],
  UKR: ["Ukraine", "🇺🇦"],
  GHA: ["Ghana", "🇬🇭"],
  FRA: ["France", "🇫🇷"],
  URU: ["Uruguay", "🇺🇾"],
  SVK: ["Slovakia", "🇸🇰"],
  CHI: ["Chile", "🇨🇱"],
  COL: ["Colombia", "🇨🇴"],
  CRC: ["Costa Rica", "🇨🇷"],
  GRE: ["Greece", "🇬🇷"],
  NGA: ["Nigeria", "🇳🇬"],
  ALG: ["Algeria", "🇩🇿"],
  CRO: ["Croatia", "🇭🇷"],
  RUS: ["Russia", "🇷🇺"],
  POL: ["Poland", "🇵🇱"],
  MAR: ["Morocco", "🇲🇦"],
  CAN: ["Canada", "🇨🇦"],
  YUG: ["Yugoslavia", "🇷🇸"],
  NOR: ["Norway", "🇳🇴"],
  ROU: ["Romania", "🇷🇴"],
  BUL: ["Bulgaria", "🇧🇬"],
  KSA: ["Saudi Arabia", "🇸🇦"],
  FRG: ["West Germany", "🇩🇪"],
  TCH: ["Czechoslovakia", "🇨🇿"],
  CMR: ["Cameroon", "🇨🇲"],
  URS: ["Soviet Union", "🇷🇺"],
  RSA: ["South Africa", "🇿🇦"],
  CIV: ["Côte d'Ivoire", "🇨🇮"],
  COD: ["DR Congo", "🇨🇩"],
  BIH: ["Bosnia-Herz.", "🇧🇦"],
  AUT: ["Austria", "🇦🇹"],
  SCO: ["Scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"],
  CPV: ["Cape Verde", "🇨🇻"],
  TUN: ["Tunisia", "🇹🇳"],
  EGY: ["Egypt", "🇪🇬"],
  IRQ: ["Iraq", "🇮🇶"],
  UZB: ["Uzbekistan", "🇺🇿"],
  NZL: ["New Zealand", "🇳🇿"],
  CZE: ["Czech Republic", "🇨🇿"],
  QAT: ["Qatar", "🇶🇦"],
  CUW: ["Curaçao", "🇨🇼"],
  JOR: ["Jordan", "🇯🇴"],
  HAI: ["Haiti", "🇭🇹"],
  PAN: ["Panama", "🇵🇦"],
  IRN: ["Iran", "🇮🇷"],
  HUN: ["Hungary", "🇭🇺"],
  CUB: ["Cuba", "🇨🇺"],
  IDN: ["Dutch East Indies", "🇮🇩"],
  BOL: ["Bolivia", "🇧🇴"],
  NIR: ["Northern Ireland", "🇬🇧"],
  WAL: ["Wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"],
  PRK: ["North Korea", "🇰🇵"],
  PER: ["Peru", "🇵🇪"],
  ISR: ["Israel", "🇮🇱"],
  ZAI: ["Zaire", "🇨🇩"],
  GDR: ["East Germany", "🇩🇪"],
  HON: ["Honduras", "🇭🇳"],
  KUW: ["Kuwait", "🇰🇼"],
  SLV: ["El Salvador", "🇸🇻"],
  TBD: ["To Be Decided", ""],
};

export const COLORS: Record<string, string> = {
  GER: "#dfe3e8",
  BRA: "#ffd21e",
  PAR: "#e2413b",
  USA: "#3f6fd6",
  MEX: "#1f9d57",
  ESP: "#e02531",
  IRL: "#16a45f",
  KOR: "#e0273f",
  ITA: "#2f8fe0",
  ENG: "#eef1f5",
  DEN: "#e23b4e",
  BEL: "#f2c11d",
  SEN: "#1fa85a",
  SWE: "#4a97e0",
  TUR: "#f0353f",
  JPN: "#2166d6",
  ARG: "#6cc2ef",
  ECU: "#ffd21e",
  POR: "#e0303f",
  NED: "#ff7a1a",
  AUS: "#f2c11d",
  SUI: "#e63535",
  UKR: "#ffd500",
  GHA: "#1fa85a",
  FRA: "#3b6ef0",
  URU: "#4aa9e0",
  SVK: "#4a7fe0",
  CHI: "#e23b4e",
  COL: "#ffd21e",
  CRC: "#e2413b",
  GRE: "#2f8fe0",
  NGA: "#1fa85a",
  ALG: "#1f9d57",
  CRO: "#e83a46",
  RUS: "#e0473a",
  POL: "#e8455a",
  MAR: "#d5313a",
  CAN: "#e0313a",
  YUG: "#3f6fd6",
  NOR: "#e0313a",
  ROU: "#f0c020",
  BUL: "#1f9d57",
  KSA: "#16824a",
  FRG: "#c9ccd1",
  TCH: "#c81f2e",
  CMR: "#1fa85a",
  URS: "#e0473a",
  RSA: "#007A4D",
  CIV: "#F77F00",
  COD: "#007FFF",
  BIH: "#0032A0",
  AUT: "#ED2939",
  SCO: "#005EB8",
  CPV: "#003893",
  TUN: "#E70013",
  EGY: "#CE1126",
  IRQ: "#CE1126",
  UZB: "#0099B5",
  NZL: "#00247D",
  CZE: "#11457E",
  QAT: "#8D1B3D",
  CUW: "#002B7F",
  JOR: "#CE1126",
  HAI: "#00209F",
  PAN: "#DA121A",
  IRN: "#239F40",
  HUN: "#CE1126",
  CUB: "#002A8F",
  IDN: "#CE1126",
  BOL: "#007A33",
  NIR: "#00529B",
  WAL: "#D30731",
  PRK: "#ED1C27",
  PER: "#D91023",
  ISR: "#00529B",
  ZAI: "#007FFF",
  GDR: "#C9CCD1",
  HON: "#0F3D7D",
  KUW: "#007A33",
  SLV: "#0047AB",
  TBD: "#71717a",
};

export const getTeamName = (code: string): string =>
  TEAMS[code] ? TEAMS[code][0] : code;

export const getTeamFlag = (code: string): string =>
  TEAMS[code] ? TEAMS[code][1] : "🏳️";

export const getTeamColor = (code: string): string =>
  COLORS[code] || "#3c4658";

export const TOURNAMENTS: Record<number, TournamentData> = {
  1934: {
    host: "Italy",
    hostFlag: "🇮🇹",
    goldenBoot: { name: "Oldřich Nejedlý", goals: 5 },
    quote: "A first star, born at home.",
    teams: [
      "ITA", "USA",
      "ESP", "BRA",
      "AUT", "FRA",
      "HUN", "EGY",
      "TCH", "SUI",
      "GER", "BEL",
      "SWE", "ARG",
      "NED", "ROU",
    ],
    r16: [
      M(7, 1, 0),
      M(3, 1, 0),
      M(3, 2, 0, null, "a.e.t."),
      M(4, 2, 0),
      M(3, 1, 0),
      M(5, 2, 0),
      M(3, 2, 0),
      M(2, 1, 0),
    ],
    qf: [M(1, 0, 0), M(2, 1, 0), M(3, 2, 0), M(2, 1, 0)],
    sf: [M(1, 0, 0), M(3, 1, 0)],
    final: [M(2, 1, 0, null, "a.e.t.")],
  },

  1938: {
    host: "France",
    hostFlag: "🇫🇷",
    goldenBoot: { name: "Leônidas", goals: 7 },
    quote: "Leônidas dazzles, Italy repeats.",
    teams: [
      "SWE", "AUT",
      "CUB", "ROU",
      "HUN", "IDN",
      "GER", "SUI",
      "FRA", "BEL",
      "ITA", "NOR",
      "BRA", "POL",
      "TCH", "NED",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 1, 0),
      M(6, 0, 0),
      M(2, 4, 1),
      M(3, 1, 0),
      M(2, 1, 0),
      M(6, 5, 0, null, "a.e.t."),
      M(3, 0, 0, null, "a.e.t."),
    ],
    qf: [M(8, 0, 0), M(2, 0, 0), M(1, 3, 1), M(2, 1, 0)],
    sf: [M(1, 5, 1), M(2, 1, 0)],
    final: [M(2, 4, 1)],
  },

  1950: {
    host: "Brazil",
    hostFlag: "🇧🇷",
    goldenBoot: { name: "Ademir", goals: 8 },
    quote: "The Maracanazo — silence heard worldwide.",
    teams: [
      "URU", "BOL",
      "SWE", "ITA",
      "BRA", "YUG",
      "ESP", "ENG",
      "SUI", "PAR",
      "CHI", "USA",
      "MEX", "AUT",
      "HUN", "FRA",
    ],
    r16: null,
    qf: [M(8, 0, 0), M(3, 2, 0), M(2, 0, 0), M(1, 0, 0)],
    sf: [M(3, 2, 0), M(6, 1, 0)],
    final: [M(2, 1, 0)],
  },

  1954: {
    host: "Switzerland",
    hostFlag: "🇨🇭",
    goldenBoot: { name: "Sándor Kocsis", goals: 11 },
    quote: "The Miracle of Bern.",
    teams: [
      "FRG", "YUG",
      "AUT", "SUI",
      "HUN", "BRA",
      "URU", "ENG",
      "FRA", "KOR",
      "TUR", "SCO",
      "TCH", "MEX",
      "ITA", "BEL",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(7, 5, 0), M(4, 2, 0), M(4, 2, 0)],
    sf: [M(6, 1, 0), M(4, 2, 0, null, "a.e.t.")],
    final: [M(3, 2, 0)],
  },

  1958: {
    host: "Sweden",
    hostFlag: "🇸🇪",
    goldenBoot: { name: "Just Fontaine", goals: 13 },
    quote: "A 17-year-old Pelé arrives.",
    teams: [
      "BRA", "WAL",
      "FRA", "NIR",
      "SWE", "URS",
      "FRG", "YUG",
      "HUN", "ENG",
      "PAR", "SCO",
      "TCH", "ARG",
      "AUT", "MEX",
    ],
    r16: null,
    qf: [M(1, 0, 0), M(4, 0, 0), M(2, 0, 0), M(1, 0, 0)],
    sf: [M(5, 2, 0), M(3, 1, 0)],
    final: [M(5, 2, 0)],
  },

  1962: {
    host: "Chile",
    hostFlag: "🇨🇱",
    goldenBoot: { name: "Garrincha / Vavá", goals: 4 },
    quote: "Garrincha carries Brazil.",
    teams: [
      "BRA", "ENG",
      "CHI", "URS",
      "TCH", "HUN",
      "YUG", "FRG",
      "COL", "ARG",
      "SUI", "ITA",
      "ESP", "MEX",
      "URU", "BUL",
    ],
    r16: null,
    qf: [M(3, 1, 0), M(2, 1, 0), M(1, 0, 0), M(1, 0, 0)],
    sf: [M(4, 2, 0), M(3, 1, 0)],
    final: [M(3, 1, 0)],
  },

  1966: {
    host: "England",
    hostFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    goldenBoot: { name: "Eusébio", goals: 9 },
    quote: "They think it's all over.",
    teams: [
      "ENG", "ARG",
      "POR", "PRK",
      "FRG", "URU",
      "URS", "HUN",
      "BRA", "ITA",
      "FRA", "ESP",
      "MEX", "BUL",
      "CHI", "SUI",
    ],
    r16: null,
    qf: [M(1, 0, 0), M(5, 3, 0), M(4, 0, 0), M(2, 1, 0)],
    sf: [M(2, 1, 0), M(2, 1, 0)],
    final: [M(4, 2, 0, null, "a.e.t.")],
  },

  1970: {
    host: "Mexico",
    hostFlag: "🇲🇽",
    goldenBoot: { name: "Gerd Müller", goals: 10 },
    quote: "Brazil's masterpiece.",
    teams: [
      "BRA", "PER",
      "URU", "URS",
      "ITA", "MEX",
      "FRG", "ENG",
      "SWE", "ROU",
      "BEL", "ISR",
      "BUL", "MAR",
      "TCH", "SLV",
    ],
    r16: null,
    qf: [M(4, 2, 0), M(1, 0, 0, null, "a.e.t."), M(4, 1, 0), M(3, 2, 0, null, "a.e.t.")],
    sf: [M(3, 1, 0), M(4, 3, 0, null, "a.e.t.")],
    final: [M(4, 1, 0)],
  },

  1974: {
    host: "West Germany",
    hostFlag: "🇩🇪",
    goldenBoot: { name: "Grzegorz Lato", goals: 7 },
    quote: "Der Kaiser prevails.",
    teams: [
      "FRG", "YUG",
      "POL", "SWE",
      "NED", "ARG",
      "BRA", "GDR",
      "SCO", "AUS",
      "URU", "BUL",
      "ITA", "HAI",
      "ZAI", "CHI",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(1, 0, 0), M(4, 0, 0), M(1, 0, 0)],
    sf: [M(1, 0, 0), M(2, 0, 0)],
    final: [M(2, 1, 0)],
  },

  1978: {
    host: "Argentina",
    hostFlag: "🇦🇷",
    goldenBoot: { name: "Mario Kempes", goals: 6 },
    quote: "Kempes in a cloud of confetti.",
    teams: [
      "ARG", "POL",
      "BRA", "PER",
      "NED", "AUT",
      "ITA", "FRG",
      "FRA", "HUN",
      "ESP", "SCO",
      "TUN", "MEX",
      "IRN", "SWE",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(3, 0, 0), M(5, 1, 0), M(2, 1, 0)],
    sf: [M(0, 0, 0), M(2, 1, 0)],
    final: [M(3, 1, 0, null, "a.e.t.")],
  },

  1982: {
    host: "Spain",
    hostFlag: "🇪🇸",
    goldenBoot: { name: "Paolo Rossi", goals: 6 },
    quote: "Rossi's redemption.",
    teams: [
      "POL", "BEL",
      "ITA", "ARG",
      "FRG", "ESP",
      "FRA", "NIR",
      "BRA", "ENG",
      "AUT", "HUN",
      "SCO", "KOR",
      "YUG", "HON",
    ],
    r16: null,
    qf: [M(3, 0, 0), M(2, 1, 0), M(2, 1, 0), M(4, 1, 0)],
    sf: [M(0, 2, 1), M(3, 3, 0, "5-4")],
    final: [M(3, 1, 0)],
  },

  1986: {
    host: "Mexico",
    hostFlag: "🇲🇽",
    goldenBoot: { name: "Gary Lineker", goals: 6 },
    quote: "Maradona's tournament.",
    teams: [
      "FRA",
      "ITA",
      "BRA",
      "POL",
      "FRG",
      "MAR",
      "MEX",
      "BUL",
      "ARG",
      "URU",
      "ENG",
      "PAR",
      "BEL",
      "URS",
      "ESP",
      "DEN",
    ],
    r16: [
      M(2, 0, 0),
      M(4, 0, 0),
      M(1, 0, 0),
      M(2, 0, 0),
      M(1, 0, 0),
      M(3, 0, 0),
      M(4, 3, 0, null, "a.e.t."),
      M(5, 1, 0),
    ],
    qf: [M(1, 1, 0, "4-3"), M(0, 0, 0, "4-1"), M(2, 1, 0), M(1, 1, 0, "5-4")],
    sf: [M(0, 2, 1), M(2, 0, 0)],
    final: [M(2, 3, 1)],
  },

  1990: {
    host: "Italy",
    hostFlag: "🇮🇹",
    goldenBoot: { name: "Salvatore Schillaci", goals: 6 },
    quote: "Schillaci's eyes.",
    teams: [
      "ARG",
      "BRA",
      "YUG",
      "ESP",
      "ITA",
      "URU",
      "IRL",
      "ROU",
      "FRG",
      "NED",
      "TCH",
      "CRC",
      "ENG",
      "BEL",
      "CMR",
      "COL",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(2, 0, 0),
      M(0, 0, 0, "5-4"),
      M(2, 1, 0),
      M(4, 1, 0),
      M(1, 0, 0, null, "a.e.t."),
      M(2, 1, 0, null, "a.e.t."),
    ],
    qf: [M(0, 0, 0, "3-2"), M(1, 0, 0), M(1, 0, 0), M(3, 2, 0, null, "a.e.t.")],
    sf: [M(1, 1, 0, "4-3"), M(1, 1, 0, "4-3")],
    final: [M(0, 1, 1)],
  },

  1994: {
    host: "United States",
    hostFlag: "🇺🇸",
    goldenBoot: { name: "Hristo Stoichkov / Oleg Salenko", goals: 6 },
    quote: "Baggio's penalty, into the sky.",
    teams: [
      "NGA",
      "ITA",
      "ESP",
      "SUI",
      "MEX",
      "BUL",
      "GER",
      "BEL",
      "NED",
      "IRL",
      "BRA",
      "USA",
      "ROU",
      "ARG",
      "SWE",
      "KSA",
    ],
    r16: [
      M(1, 2, 1, null, "a.e.t."),
      M(3, 0, 0),
      M(1, 1, 1, "1-3"),
      M(3, 2, 0),
      M(2, 0, 0),
      M(1, 0, 0),
      M(3, 2, 0),
      M(3, 1, 0),
    ],
    qf: [M(2, 1, 0), M(2, 1, 0), M(2, 3, 1), M(2, 2, 1, "4-5")],
    sf: [M(2, 1, 0), M(1, 0, 0)],
    final: [M(0, 0, 1, "2-3")],
  },

  1998: {
    host: "France",
    hostFlag: "🇫🇷",
    goldenBoot: { name: "Davor Šuker", goals: 6 },
    quote: "Les Bleus, unstoppable at home.",
    teams: [
      "BRA",
      "CHI",
      "DEN",
      "NGA",
      "NED",
      "YUG",
      "ARG",
      "ENG",
      "ITA",
      "NOR",
      "FRA",
      "PAR",
      "GER",
      "MEX",
      "ROU",
      "CRO",
    ],
    r16: [
      M(4, 1, 0),
      M(4, 1, 0),
      M(2, 1, 0),
      M(2, 2, 0, "4-3"),
      M(1, 0, 0),
      M(1, 0, 0, null, "golden goal"),
      M(2, 1, 0),
      M(0, 1, 1),
    ],
    qf: [M(3, 2, 0), M(2, 1, 0), M(0, 0, 1, "3-4"), M(0, 3, 1)],
    sf: [M(1, 1, 0, "4-2"), M(2, 1, 0)],
    final: [M(0, 3, 1)],
  },

  2002: {
    host: "South Korea / Japan",
    hostFlag: "🇰🇷 🇯🇵",
    goldenBoot: { name: "Ronaldo", goals: 8 },
    quote: "Ronaldo's redemption.",
    teams: [
      "GER",
      "PAR",
      "USA",
      "MEX",
      "ESP",
      "IRL",
      "KOR",
      "ITA",
      "ENG",
      "DEN",
      "BRA",
      "BEL",
      "SEN",
      "SWE",
      "TUR",
      "JPN",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 0, 0),
      M(1, 1, 0, "3-2"),
      M(2, 1, 0, null, "a.e.t."),
      M(3, 0, 0),
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(1, 0, 0),
    ],
    qf: [
      M(1, 0, 0),
      M(0, 0, 1, "3-5"),
      M(1, 2, 1),
      M(0, 1, 1, null, "golden goal"),
    ],
    sf: [M(1, 0, 0), M(1, 0, 0)],
    final: [M(0, 2, 1)],
  },

  2006: {
    host: "Germany",
    hostFlag: "🇩🇪",
    goldenBoot: { name: "Miroslav Klose", goals: 5 },
    quote: "Zidane's headbutt.",
    teams: [
      "GER",
      "SWE",
      "ARG",
      "MEX",
      "ITA",
      "AUS",
      "SUI",
      "UKR",
      "ENG",
      "ECU",
      "POR",
      "NED",
      "BRA",
      "GHA",
      "ESP",
      "FRA",
    ],
    r16: [
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(1, 0, 0),
      M(0, 0, 1, "0-3"),
      M(1, 0, 0),
      M(1, 0, 0),
      M(3, 0, 0),
      M(1, 3, 1),
    ],
    qf: [M(1, 1, 0, "4-2"), M(3, 0, 0), M(0, 0, 1, "1-3"), M(0, 1, 1)],
    sf: [M(0, 2, 1, null, "a.e.t."), M(0, 1, 1)],
    final: [M(1, 1, 0, "5-3")],
  },

  2010: {
    host: "South Africa",
    hostFlag: "🇿🇦",
    goldenBoot: { name: "Thomas Müller", goals: 5 },
    quote: "Iniesta, forever.",
    teams: [
      "URU",
      "KOR",
      "USA",
      "GHA",
      "NED",
      "SVK",
      "BRA",
      "CHI",
      "GER",
      "ENG",
      "ARG",
      "MEX",
      "PAR",
      "JPN",
      "ESP",
      "POR",
    ],
    r16: [
      M(2, 1, 0),
      M(1, 2, 1, null, "a.e.t."),
      M(2, 1, 0),
      M(3, 0, 0),
      M(4, 1, 0),
      M(3, 1, 0),
      M(0, 0, 0, "5-3"),
      M(1, 0, 0),
    ],
    qf: [
      M(1, 1, 0, "4-2", " a.e.t."),
      M(2, 1, 0),
      M(4, 0, 0),
      M(0, 1, 1),
    ],
    sf: [M(2, 3, 1), M(0, 1, 1)],
    final: [M(0, 1, 1, null, "a.e.t.")],
  },

  2014: {
    host: "Brazil",
    hostFlag: "🇧🇷",
    goldenBoot: { name: "James Rodríguez", goals: 6 },
    quote: "Götze seals the fourth star.",
    teams: [
      "BRA",
      "CHI",
      "COL",
      "URU",
      "FRA",
      "NGA",
      "GER",
      "ALG",
      "NED",
      "MEX",
      "CRC",
      "GRE",
      "ARG",
      "SUI",
      "BEL",
      "USA",
    ],
    r16: [
      M(1, 1, 0, "3-2"),
      M(2, 0, 0),
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(2, 1, 0),
      M(1, 1, 0, "5-3"),
      M(1, 0, 0, null, "a.e.t."),
      M(2, 1, 0, null, "a.e.t."),
    ],
    qf: [M(2, 1, 0), M(0, 1, 1), M(0, 0, 0, "4-3"), M(1, 0, 0)],
    sf: [M(1, 7, 1), M(0, 0, 1, "2-4")],
    final: [M(1, 0, 0, null, "a.e.t.")],
  },

  2018: {
    host: "Russia",
    hostFlag: "🇷🇺",
    goldenBoot: { name: "Harry Kane", goals: 6 },
    quote: "Mbappé arrives.",
    teams: [
      "URU",
      "POR",
      "FRA",
      "ARG",
      "BRA",
      "MEX",
      "BEL",
      "JPN",
      "SWE",
      "SUI",
      "COL",
      "ENG",
      "ESP",
      "RUS",
      "CRO",
      "DEN",
    ],
    r16: [
      M(2, 1, 0),
      M(4, 3, 0),
      M(2, 0, 0),
      M(3, 2, 0),
      M(1, 0, 0),
      M(1, 1, 1, "3-4"),
      M(1, 1, 1, "3-4"),
      M(1, 1, 0, "3-2"),
    ],
    qf: [M(0, 2, 1), M(1, 2, 1), M(0, 2, 1), M(2, 2, 1, "3-4")],
    sf: [M(1, 0, 0), M(1, 2, 1, null, "a.e.t.")],
    final: [M(4, 2, 0)],
  },

  2022: {
    host: "Qatar",
    hostFlag: "🇶🇦",
    goldenBoot: { name: "Kylian Mbappé", goals: 8 },
    quote: "Messi. At last.",
    teams: [
      "NED",
      "USA",
      "ARG",
      "AUS",
      "JPN",
      "CRO",
      "BRA",
      "KOR",
      "MAR",
      "ESP",
      "POR",
      "SUI",
      "ENG",
      "SEN",
      "FRA",
      "POL",
    ],
    r16: [
      M(3, 1, 0),
      M(2, 1, 0),
      M(1, 1, 1, "1-3"),
      M(4, 1, 0),
      M(0, 0, 0, "3-0"),
      M(6, 1, 0),
      M(3, 0, 0),
      M(3, 1, 0),
    ],
    qf: [M(2, 2, 1, "3-4"), M(1, 1, 0, "4-2"), M(1, 0, 0), M(1, 2, 1)],
    sf: [M(3, 0, 0), M(0, 2, 1)],
    final: [M(3, 3, 0, "4-2")],
  },

  2026: {
    host: "USA · Canada · Mexico",
    hostFlag: "🇺🇸 🇨🇦 🇲🇽",
    goldenBoot: null,
    quote: null,
    seeded: false,
    // Sourced from https://worldcup26.ir (worldcup2026 REST API) — see
    // scripts/fetch-worldcup26.ts. Bracket-feed order is deterministic via
    // that API's "Winner Match N" labels, not just fixture date order.
    teams: [
      "PAR", "FRA",
      "CAN", "MAR",
      "BRA", "NOR",
      "MEX", "ENG",
      "POR", "ESP",
      "USA", "BEL",
      "ARG", "EGY",
      "SUI", "COL",
    ],
    r32: [
      { ta: "GER", tb: "PAR", s: [1, 1], w: 1, p: "3-4", g: [["Kai Havertz 54'"], ["Julio Enciso 42'"]], date: "Jun 29 · 16:30" },
      { ta: "FRA", tb: "SWE", s: [3, 0], w: 0, g: [["Kylian Mbappé 45'", "Bradley Barcola 53'", "Kylian Mbappé 74'"], []], date: "Jun 30 · 17:00" },
      { ta: "RSA", tb: "CAN", s: [0, 1], w: 1, g: [[], ["Stephen Eustáquio 90+2'"]], date: "Jun 28 · 12:00" },
      { ta: "NED", tb: "MAR", s: [1, 1], w: 1, p: "2-3", g: [["Cody Gakpo 72'"], ["Issa Diop 90+1'"]], date: "Jun 29 · 19:00" },
      { ta: "BRA", tb: "JPN", s: [2, 1], w: 0, g: [["Casemiro 56'", "Gabriel Martinelli 90+5'"], ["Kaishū Sano 29'"]], date: "Jun 29 · 12:00" },
      { ta: "CIV", tb: "NOR", s: [1, 2], w: 1, g: [["Amad Diallo 74'"], ["Antonio Nusa 39'", "Erling Haaland 86'"]], date: "Jun 30 · 12:00" },
      { ta: "MEX", tb: "ECU", s: [2, 0], w: 0, g: [["Julián Quiñones 22'", "Raúl Jiménez 31'"], []], date: "Jun 30 · 19:00" },
      { ta: "ENG", tb: "COD", s: [2, 1], w: 0, g: [["Harry Kane 75'", "Harry Kane 86'"], ["Braian Sipnga 7'"]], date: "Jul 1 · 12:00" },
      { ta: "POR", tb: "CRO", s: [2, 1], w: 0, g: [["Gonçalo Ramos 90+4'"], ["Ivan Perišić 53'"]], date: "Jul 2 · 19:00" },
      { ta: "ESP", tb: "AUT", s: [3, 0], w: 0, g: [["Mikel Oyarzabal 36'", "Pedro Porro 66'", "Mikel Oyarzabal 89'"], []], date: "Jul 2 · 12:00" },
      { ta: "USA", tb: "BIH", s: [2, 0], w: 0, g: [["Folarin Balogun 45'", "Malik Tillman 82'"], []], date: "Jul 1 · 17:00" },
      { ta: "BEL", tb: "SEN", s: [3, 2], w: 0, x: "a.e.t.", g: [["Romelu Lukaku 86'", "Youri Tielemans 89'", "Youri Tielemans 125(P)'"], ["Habib Diarra 25'", "Ismaïla Sarr 51'"]], date: "Jul 1 · 13:00" },
      { ta: "ARG", tb: "CPV", s: [3, 2], w: 0, x: "a.e.t.", date: "Jul 3 · 18:00" },
      { ta: "AUS", tb: "EGY", s: [1, 1], w: 1, p: "2-4", g: [["Mohamed Hany 55'"], ["Emam Ashour 13'"]], date: "Jul 3 · 13:00" },
      { ta: "SUI", tb: "ALG", s: [2, 0], w: 0, g: [["Breel Embolo 10'", "Dan Ndoye 46'"], []], date: "Jul 2 · 20:00" },
      { ta: "COL", tb: "GHA", s: [1, 0], w: 0, date: "Jul 3 · 20:30" },
    ],
    r16: [
      // France 1–0 Paraguay (R16, Jul 4) — France advance
      M(0, 1, 1, null, null, [[], ["Kylian Mbappé 70' (pen.)"]]),
      M(0, 3, 1, null, null, [[], ["Azzedine Ounahi 50'", "Azzedine Ounahi 82'", "Soufiane Rahimi 90+8'"]]),
      null, null, null, null, null, null,
    ],
    qf: null,
    sf: null,
    final: null,
  },
};
