import { Match, TournamentData } from "./types";

const M = (
  top: number,
  bot: number,
  w: number,
  p: string | null = null,
  x: string | null = null,
  g: [string[], string[]] | null = null
): Match => ({
  s: [top, bot],
  w,
  p: p || null,
  x: x || null,
  g: g || null,
});

export const TEAMS: Record<string, [string, string]> = {
  GER: ["Germany", "🇩🇪"],
  BRA: ["Brazil", "🇧🇷"],
  PAR: ["Paraguay", "🇵🇾"],
  USA: ["United States", "🇺🇸"],
  MEX: ["Mexico", "🇲🇽"],
  ESP: ["Spain", "🇪🇸"],
  IRL: ["Rep. Ireland", "🇮🇪"],
  KOR: ["South Korea", "🇰🇷"],
  ITA: ["Italy", "🇮🇹"],
  ENG: ["England", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"],
  DEN: ["Denmark", "🇩🇰"],
  BEL: ["Belgium", "🇧🇪"],
  SEN: ["Senegal", "🇸🇳"],
  SWE: ["Sweden", "🇸🇪"],
  TUR: ["Türkiye", "🇹🇷"],
  JPN: ["Japan", "🇯🇵"],
  ARG: ["Argentina", "🇦🇷"],
  ECU: ["Ecuador", "🇪🇨"],
  POR: ["Portugal", "🇵🇹"],
  NED: ["Netherlands", "🇳🇱"],
  AUS: ["Australia", "🇦🇺"],
  SUI: ["Switzerland", "🇨🇭"],
  UKR: ["Ukraine", "🇺🇦"],
  GHA: ["Ghana", "🇬🇭"],
  FRA: ["France", "🇫🇷"],
  URU: ["Uruguay", "🇺🇾"],
  SVK: ["Slovakia", "🇸🇰"],
  CHI: ["Chile", "🇨🇱"],
  COL: ["Colombia", "🇨🇴"],
  CRC: ["Costa Rica", "🇨🇷"],
  GRE: ["Greece", "🇬🇷"],
  NGA: ["Nigeria", "🇳🇬"],
  ALG: ["Algeria", "🇩🇿"],
  CRO: ["Croatia", "🇭🇷"],
  RUS: ["Russia", "🇷🇺"],
  POL: ["Poland", "🇵🇱"],
  MAR: ["Morocco", "🇲🇦"],
  CAN: ["Canada", "🇨🇦"],
  YUG: ["Yugoslavia", "🇷🇸"],
  NOR: ["Norway", "🇳🇴"],
  ROU: ["Romania", "🇷🇴"],
  BUL: ["Bulgaria", "🇧🇬"],
  KSA: ["Saudi Arabia", "🇸🇦"],
  FRG: ["West Germany", "🇩🇪"],
  TCH: ["Czechoslovakia", "🇨🇿"],
  CMR: ["Cameroon", "🇨🇲"],
  URS: ["Soviet Union", "🇷🇺"],
  RSA: ["South Africa", "🇿🇦"],
  CIV: ["Côte d'Ivoire", "🇨🇮"],
  COD: ["DR Congo", "🇨🇩"],
  BIH: ["Bosnia-Herz.", "🇧🇦"],
  AUT: ["Austria", "🇦🇹"],
  SCO: ["Scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"],
  CPV: ["Cape Verde", "🇨🇻"],
  TUN: ["Tunisia", "🇹🇳"],
  EGY: ["Egypt", "🇪🇬"],
  IRQ: ["Iraq", "🇮🇶"],
  UZB: ["Uzbekistan", "🇺🇿"],
  NZL: ["New Zealand", "🇳🇿"],
  CZE: ["Czech Republic", "🇨🇿"],
  QAT: ["Qatar", "🇶🇦"],
  CUW: ["Curaçao", "🇨🇼"],
  JOR: ["Jordan", "🇯🇴"],
  HAI: ["Haiti", "🇭🇹"],
  PAN: ["Panama", "🇵🇦"],
  IRN: ["Iran", "🇮🇷"],
  HUN: ["Hungary", "🇭🇺"],
  CUB: ["Cuba", "🇨🇺"],
  IDN: ["Dutch East Indies", "🇮🇩"],
  BOL: ["Bolivia", "🇧🇴"],
  NIR: ["Northern Ireland", "🇬🇧"],
  WAL: ["Wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"],
  PRK: ["North Korea", "🇰🇵"],
  PER: ["Peru", "🇵🇪"],

  ZAI: ["Zaire", "🇨🇩"],
  GDR: ["East Germany", "🇩🇪"],
  HON: ["Honduras", "🇭🇳"],
  KUW: ["Kuwait", "🇰🇼"],
  SLV: ["El Salvador", "🇸🇻"],
  PLE: ["Palestine", "🇵🇸"],
  TBD: ["To Be Decided", ""],
};

export const COLORS: Record<string, string> = {
  GER: "#dfe3e8",
  BRA: "#ffd21e",
  PAR: "#e2413b",
  USA: "#3f6fd6",
  MEX: "#1f9d57",
  ESP: "#e02531",
  IRL: "#16a45f",
  KOR: "#e0273f",
  ITA: "#2f8fe0",
  ENG: "#eef1f5",
  DEN: "#e23b4e",
  BEL: "#f2c11d",
  SEN: "#1fa85a",
  SWE: "#4a97e0",
  TUR: "#f0353f",
  JPN: "#2166d6",
  ARG: "#6cc2ef",
  ECU: "#ffd21e",
  POR: "#e0303f",
  NED: "#ff7a1a",
  AUS: "#f2c11d",
  SUI: "#e63535",
  UKR: "#ffd500",
  GHA: "#1fa85a",
  FRA: "#3b6ef0",
  URU: "#4aa9e0",
  SVK: "#4a7fe0",
  CHI: "#e23b4e",
  COL: "#ffd21e",
  CRC: "#e2413b",
  GRE: "#2f8fe0",
  NGA: "#1fa85a",
  ALG: "#1f9d57",
  CRO: "#e83a46",
  RUS: "#e0473a",
  POL: "#e8455a",
  MAR: "#d5313a",
  CAN: "#e0313a",
  YUG: "#3f6fd6",
  NOR: "#e0313a",
  ROU: "#f0c020",
  BUL: "#1f9d57",
  KSA: "#16824a",
  FRG: "#c9ccd1",
  TCH: "#c81f2e",
  CMR: "#1fa85a",
  URS: "#e0473a",
  RSA: "#007A4D",
  CIV: "#F77F00",
  COD: "#007FFF",
  BIH: "#0032A0",
  AUT: "#ED2939",
  SCO: "#005EB8",
  CPV: "#003893",
  TUN: "#E70013",
  EGY: "#CE1126",
  IRQ: "#CE1126",
  UZB: "#0099B5",
  NZL: "#00247D",
  CZE: "#11457E",
  QAT: "#8D1B3D",
  CUW: "#002B7F",
  JOR: "#CE1126",
  HAI: "#00209F",
  PAN: "#DA121A",
  IRN: "#239F40",
  HUN: "#CE1126",
  CUB: "#002A8F",
  IDN: "#CE1126",
  BOL: "#007A33",
  NIR: "#00529B",
  WAL: "#D30731",
  PRK: "#ED1C27",
  PER: "#D91023",

  ZAI: "#007FFF",
  GDR: "#C9CCD1",
  HON: "#0F3D7D",
  KUW: "#007A33",
  SLV: "#0047AB",
  PLE: "#CE1126",
  TBD: "#71717a",
};

export const getTeamName = (code: string): string =>
  TEAMS[code] ? TEAMS[code][0] : code;

export const getTeamFlag = (code: string): string =>
  TEAMS[code] ? TEAMS[code][1] : "🏳️";

export const getTeamColor = (code: string): string =>
  COLORS[code] || "#3c4658";

// ── Multi-colour palettes ────────────────────────────────────────────────────
// COLORS holds one tuned primary per nation (used for the dot, bars, etc.).
// For the country-page ambient aurora we want 2–3 of the nation's dominant
// flag colours. TEAM_ACCENTS lists the secondary/tertiary flag colours; nations
// with a single-colour identity (e.g. red-and-white flags) get a harmonious
// hue-rotated tone instead, so every page still blends multiple stops.
export const TEAM_ACCENTS: Record<string, string[]> = {
  GER: ["#d00000", "#ffce00"], FRG: ["#d00000", "#ffce00"], GDR: ["#d00000", "#ffce00"],
  BRA: ["#009739", "#3d3f8f"], PAR: ["#0038a8"], USA: ["#b22234"], MEX: ["#ce1126"],
  ESP: ["#ffc400"], IRL: ["#ff883e"], KOR: ["#0047a0"], ITA: ["#008c45", "#cd212a"],
  ENG: ["#ce1124"], BEL: ["#c8102e"], SEN: ["#fdef42", "#e31b23"], SWE: ["#fecc00"],
  ARG: ["#f6b40e"], ECU: ["#0072ce", "#ef3340"], POR: ["#046a38"],
  NED: ["#21468b", "#ae1c28"], AUS: ["#00843d"], UKR: ["#0057b7"],
  GHA: ["#fcd116", "#ce1126"], FRA: ["#ef4135"], URU: ["#f6b40e"], SVK: ["#ee1c25"],
  CHI: ["#0039a6"], COL: ["#003893", "#ce1126"], CRC: ["#002b7f"], ALG: ["#d21034"],
  CRO: ["#171796"], RUS: ["#0039a6"], MAR: ["#006233"], YUG: ["#c6363c"],
  NOR: ["#00205b"], ROU: ["#002b7f", "#ce1126"], BUL: ["#d62612"], TCH: ["#11457e"],
  CMR: ["#fcd116", "#ce1126"], URS: ["#ffd700"], RSA: ["#ffb612", "#002395"],
  CIV: ["#009e60"], COD: ["#f7d618", "#ce1021"], BIH: ["#fecb00"],
  CPV: ["#cf2027", "#f7d116"], IRQ: ["#007a3d"], UZB: ["#1eb53a", "#ce1126"],
  NZL: ["#c8102e"], CZE: ["#d7141a"], CUW: ["#f9d90f"], JOR: ["#007a3d"],
  HAI: ["#d21034"], PAN: ["#005293"], IRN: ["#da0000"], HUN: ["#477050"],
  CUB: ["#cb1515"], IDN: ["#21468b"], BOL: ["#f9e300", "#d52b1e"], NIR: ["#cf142b"],
  WAL: ["#00ad36"], PRK: ["#024fa2"], ZAI: ["#fdd116", "#0d9b49"], KUW: ["#ce1126"],
  PLE: ["#009736", "#e4312b"],
};

const clamp = (n: number, lo = 0, hi = 100) => Math.max(lo, Math.min(hi, n));

function hexToHsl(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let hue = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    hue = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
    hue *= 60;
  }
  return [hue, s * 100, l * 100];
}

function hslToHex(h: number, s: number, l: number): string {
  s /= 100; l /= 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const to = (n: number) => Math.round(255 * f(n)).toString(16).padStart(2, "0");
  return `#${to(0)}${to(8)}${to(4)}`;
}

// Rotate a colour's hue (and optionally nudge lightness) — used to synthesise a
// second aurora tone for nations without a distinct accent colour.
function rotateHue(hex: string, deg: number, dl = 0): string {
  const [h, s, l] = hexToHsl(hex);
  return hslToHex((h + deg + 360) % 360, s, clamp(l + dl));
}

// 2–3 dominant colours for a nation, primary first. Falls back to a hue-rotated
// tone when no curated accent exists so the aurora always has depth.
export const getTeamPalette = (code: string): string[] => {
  const base = getTeamColor(code);
  const accents = TEAM_ACCENTS[code];
  const palette = accents?.length ? [base, ...accents] : [base, rotateHue(base, 26, -8)];
  return palette.slice(0, 3);
};

export const TOURNAMENTS: Record<number, TournamentData> = {
  1930: {
    host: "Uruguay",
    hostFlag: "🇺🇾",
    goldenBoot: { name: "Guillermo Stábile", goals: 8 },
    quote: "Where it all began.",
    teams: [
      "ARG", "CHI",
      "USA", "BEL",
      "URU", "PER",
      "YUG", "BOL",
    ],
    r16: null,
    qf: [M(3, 1, 0), M(3, 0, 0), M(1, 0, 0), M(4, 0, 0)],
    sf: [M(6, 1, 0), M(6, 1, 0)],
    final: [M(2, 4, 1)],
  },

  1934: {
    host: "Italy",
    hostFlag: "🇮🇹",
    goldenBoot: { name: "Oldřich Nejedlý", goals: 5 },
    quote: "A first star, born at home.",
    teams: [
      "ITA", "USA",
      "ESP", "BRA",
      "AUT", "FRA",
      "HUN", "EGY",
      "TCH", "SUI",
      "GER", "BEL",
      "SWE", "ARG",
      "NED", "ROU",
    ],
    r16: [
      M(7, 1, 0),
      M(3, 1, 0),
      M(3, 2, 0, null, "a.e.t."),
      M(4, 2, 0),
      M(3, 1, 0),
      M(5, 2, 0),
      M(3, 2, 0),
      M(2, 1, 0),
    ],
    qf: [M(1, 0, 0), M(2, 1, 0), M(3, 2, 0), M(2, 1, 0)],
    sf: [M(1, 0, 0), M(3, 1, 0)],
    final: [M(2, 1, 0, null, "a.e.t.")],
  },

  1938: {
    host: "France",
    hostFlag: "🇫🇷",
    goldenBoot: { name: "Leônidas", goals: 8 },
    quote: "Leônidas dazzles, Italy repeats.",
    teams: [
      "SWE", "AUT",
      "CUB", "ROU",
      "HUN", "IDN",
      "GER", "SUI",
      "FRA", "BEL",
      "ITA", "NOR",
      "BRA", "POL",
      "TCH", "NED",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 1, 0),
      M(6, 0, 0),
      M(2, 4, 1),
      M(3, 1, 0),
      M(2, 1, 0),
      M(6, 5, 0, null, "a.e.t."),
      M(3, 0, 0, null, "a.e.t."),
    ],
    qf: [M(8, 0, 0), M(2, 0, 0), M(1, 3, 1), M(2, 1, 0)],
    sf: [M(1, 5, 1), M(2, 1, 0)],
    final: [M(2, 4, 1)],
  },

  1950: {
    host: "Brazil",
    hostFlag: "🇧🇷",
    goldenBoot: { name: "Ademir", goals: 8 },
    quote: "The Maracanazo — silence heard worldwide.",
    teams: [
      "URU", "BOL",
      "SWE", "ITA",
      "BRA", "YUG",
      "ESP", "ENG",
      "SUI", "PAR",
      "CHI", "USA",
      "MEX", "AUT",
      "HUN", "FRA",
    ],
    r16: null,
    qf: [M(8, 0, 0), M(3, 2, 0), M(2, 0, 0), M(1, 0, 0)],
    sf: [M(3, 2, 0), M(6, 1, 0)],
    final: [M(2, 1, 0)],
  },

  1954: {
    host: "Switzerland",
    hostFlag: "🇨🇭",
    goldenBoot: { name: "Sándor Kocsis", goals: 11 },
    quote: "The Miracle of Bern.",
    teams: [
      "FRG", "YUG",
      "AUT", "SUI",
      "HUN", "BRA",
      "URU", "ENG",
      "FRA", "KOR",
      "TUR", "SCO",
      "TCH", "MEX",
      "ITA", "BEL",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(7, 5, 0), M(4, 2, 0), M(4, 2, 0)],
    sf: [M(6, 1, 0), M(4, 2, 0, null, "a.e.t.")],
    final: [M(3, 2, 0)],
  },

  1958: {
    host: "Sweden",
    hostFlag: "🇸🇪",
    goldenBoot: { name: "Just Fontaine", goals: 13 },
    quote: "A 17-year-old Pelé arrives.",
    teams: [
      "BRA", "WAL",
      "FRA", "NIR",
      "SWE", "URS",
      "FRG", "YUG",
      "HUN", "ENG",
      "PAR", "SCO",
      "TCH", "ARG",
      "AUT", "MEX",
    ],
    r16: null,
    qf: [M(1, 0, 0), M(4, 0, 0), M(2, 0, 0), M(1, 0, 0)],
    sf: [M(5, 2, 0), M(3, 1, 0)],
    final: [M(5, 2, 0)],
  },

  1962: {
    host: "Chile",
    hostFlag: "🇨🇱",
    goldenBoot: { name: "Flórián Albert", goals: 4 },
    quote: "Garrincha carries Brazil.",
    teams: [
      "BRA", "ENG",
      "CHI", "URS",
      "TCH", "HUN",
      "YUG", "FRG",
      "COL", "ARG",
      "SUI", "ITA",
      "ESP", "MEX",
      "URU", "BUL",
    ],
    r16: null,
    qf: [M(3, 1, 0), M(2, 1, 0), M(1, 0, 0), M(1, 0, 0)],
    sf: [M(4, 2, 0), M(3, 1, 0)],
    final: [M(3, 1, 0)],
  },

  1966: {
    host: "England",
    hostFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    goldenBoot: { name: "Eusébio", goals: 9 },
    quote: "They think it's all over.",
    teams: [
      "ENG", "ARG",
      "POR", "PRK",
      "FRG", "URU",
      "URS", "HUN",
      "BRA", "ITA",
      "FRA", "ESP",
      "MEX", "BUL",
      "CHI", "SUI",
    ],
    r16: null,
    qf: [M(1, 0, 0), M(5, 3, 0), M(4, 0, 0), M(2, 1, 0)],
    sf: [M(2, 1, 0), M(2, 1, 0)],
    final: [M(4, 2, 0, null, "a.e.t.")],
  },

  1970: {
    host: "Mexico",
    hostFlag: "🇲🇽",
    goldenBoot: { name: "Gerd Müller", goals: 10 },
    quote: "Brazil's masterpiece.",
    teams: [
      "BRA", "PER",
      "URU", "URS",
      "ITA", "MEX",
      "FRG", "ENG",
      "SWE", "ROU",
      "BEL", "TBD",
      "BUL", "MAR",
      "TCH", "SLV",
    ],
    r16: null,
    qf: [M(4, 2, 0), M(1, 0, 0, null, "a.e.t."), M(4, 1, 0), M(3, 2, 0, null, "a.e.t.")],
    sf: [M(3, 1, 0), M(4, 3, 0, null, "a.e.t.")],
    final: [M(4, 1, 0)],
  },

  1974: {
    host: "West Germany",
    hostFlag: "🇩🇪",
    goldenBoot: { name: "Grzegorz Lato", goals: 7 },
    quote: "Der Kaiser prevails.",
    teams: [
      "FRG", "YUG",
      "POL", "SWE",
      "NED", "ARG",
      "BRA", "GDR",
      "SCO", "AUS",
      "URU", "BUL",
      "ITA", "HAI",
      "ZAI", "CHI",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(1, 0, 0), M(4, 0, 0), M(1, 0, 0)],
    sf: [M(1, 0, 0), M(2, 0, 0)],
    final: [M(2, 1, 0)],
  },

  1978: {
    host: "Argentina",
    hostFlag: "🇦🇷",
    goldenBoot: { name: "Mario Kempes", goals: 6 },
    quote: "Kempes in a cloud of confetti.",
    teams: [
      "ARG", "POL",
      "BRA", "PER",
      "NED", "AUT",
      "ITA", "FRG",
      "FRA", "HUN",
      "ESP", "SCO",
      "TUN", "MEX",
      "IRN", "SWE",
    ],
    r16: null,
    qf: [M(2, 0, 0), M(3, 0, 0), M(5, 1, 0), M(2, 1, 0)],
    sf: [M(0, 0, 0), M(2, 1, 0)],
    final: [M(3, 1, 0, null, "a.e.t.")],
  },

  1982: {
    host: "Spain",
    hostFlag: "🇪🇸",
    goldenBoot: { name: "Paolo Rossi", goals: 6 },
    quote: "Rossi's redemption.",
    teams: [
      "POL", "BEL",
      "ITA", "ARG",
      "FRG", "ESP",
      "FRA", "NIR",
      "BRA", "ENG",
      "AUT", "HUN",
      "SCO", "KOR",
      "YUG", "HON",
    ],
    r16: null,
    qf: [M(3, 0, 0), M(2, 1, 0), M(2, 1, 0), M(4, 1, 0)],
    sf: [M(0, 2, 1), M(3, 3, 0, "5-4")],
    final: [M(3, 1, 0)],
  },

  1986: {
    host: "Mexico",
    hostFlag: "🇲🇽",
    goldenBoot: { name: "Gary Lineker", goals: 6 },
    quote: "Maradona's tournament.",
    teams: [
      "FRA",
      "ITA",
      "BRA",
      "POL",
      "FRG",
      "MAR",
      "MEX",
      "BUL",
      "ARG",
      "URU",
      "ENG",
      "PAR",
      "BEL",
      "URS",
      "ESP",
      "DEN",
    ],
    r16: [
      M(2, 0, 0),
      M(4, 0, 0),
      M(1, 0, 0),
      M(2, 0, 0),
      M(1, 0, 0),
      M(3, 0, 0),
      M(4, 3, 0, null, "a.e.t."),
      M(5, 1, 0),
    ],
    qf: [M(1, 1, 0, "4-3"), M(0, 0, 0, "4-1"), M(2, 1, 0), M(1, 1, 0, "5-4")],
    sf: [M(0, 2, 1), M(2, 0, 0)],
    final: [M(2, 3, 1)],
  },

  1990: {
    host: "Italy",
    hostFlag: "🇮🇹",
    goldenBoot: { name: "Salvatore Schillaci", goals: 6 },
    quote: "Schillaci's eyes.",
    teams: [
      "ARG",
      "BRA",
      "YUG",
      "ESP",
      "ITA",
      "URU",
      "IRL",
      "ROU",
      "FRG",
      "NED",
      "TCH",
      "CRC",
      "ENG",
      "BEL",
      "CMR",
      "COL",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(2, 0, 0),
      M(0, 0, 0, "5-4"),
      M(2, 1, 0),
      M(4, 1, 0),
      M(1, 0, 0, null, "a.e.t."),
      M(2, 1, 0, null, "a.e.t."),
    ],
    qf: [M(0, 0, 0, "3-2"), M(1, 0, 0), M(1, 0, 0), M(3, 2, 0, null, "a.e.t.")],
    sf: [M(1, 1, 0, "4-3"), M(1, 1, 0, "4-3")],
    final: [M(0, 1, 1)],
  },

  1994: {
    host: "United States",
    hostFlag: "🇺🇸",
    goldenBoot: { name: "Oleg Salenko", goals: 6 },
    goldenGlove: { name: "Michel Preud'homme" },
    quote: "Baggio's penalty, into the sky.",
    teams: [
      "NGA",
      "ITA",
      "ESP",
      "SUI",
      "MEX",
      "BUL",
      "GER",
      "BEL",
      "NED",
      "IRL",
      "BRA",
      "USA",
      "ROU",
      "ARG",
      "SWE",
      "KSA",
    ],
    r16: [
      M(1, 2, 1, null, "a.e.t."),
      M(3, 0, 0),
      M(1, 1, 1, "1-3"),
      M(3, 2, 0),
      M(2, 0, 0),
      M(1, 0, 0),
      M(3, 2, 0),
      M(3, 1, 0),
    ],
    qf: [M(2, 1, 0), M(2, 1, 0), M(2, 3, 1), M(2, 2, 1, "4-5")],
    sf: [M(2, 1, 0), M(1, 0, 0)],
    final: [M(0, 0, 1, "2-3")],
  },

  1998: {
    host: "France",
    hostFlag: "🇫🇷",
    goldenBoot: { name: "Davor Šuker", goals: 6 },
    goldenGlove: { name: "Fabien Barthez" },
    quote: "Les Bleus, unstoppable at home.",
    teams: [
      "BRA",
      "CHI",
      "DEN",
      "NGA",
      "NED",
      "YUG",
      "ARG",
      "ENG",
      "ITA",
      "NOR",
      "FRA",
      "PAR",
      "GER",
      "MEX",
      "ROU",
      "CRO",
    ],
    r16: [
      M(4, 1, 0),
      M(4, 1, 0),
      M(2, 1, 0),
      M(2, 2, 0, "4-3"),
      M(1, 0, 0),
      M(1, 0, 0, null, "golden goal"),
      M(2, 1, 0),
      M(0, 1, 1),
    ],
    qf: [M(3, 2, 0), M(2, 1, 0), M(0, 0, 1, "3-4"), M(0, 3, 1)],
    sf: [M(1, 1, 0, "4-2"), M(2, 1, 0)],
    final: [M(0, 3, 1)],
  },

  2002: {
    host: "South Korea / Japan",
    hostFlag: "🇰🇷 🇯🇵",
    goldenBoot: { name: "Ronaldo", goals: 8 },
    goldenGlove: { name: "Oliver Kahn" },
    quote: "Ronaldo's redemption.",
    teams: [
      "GER",
      "PAR",
      "USA",
      "MEX",
      "ESP",
      "IRL",
      "KOR",
      "ITA",
      "ENG",
      "DEN",
      "BRA",
      "BEL",
      "SEN",
      "SWE",
      "TUR",
      "JPN",
    ],
    r16: [
      M(1, 0, 0),
      M(2, 0, 0),
      M(1, 1, 0, "3-2"),
      M(2, 1, 0, null, "a.e.t."),
      M(3, 0, 0),
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(1, 0, 0),
    ],
    qf: [
      M(1, 0, 0),
      M(0, 0, 1, "3-5"),
      M(1, 2, 1),
      M(0, 1, 1, null, "golden goal"),
    ],
    sf: [M(1, 0, 0), M(1, 0, 0)],
    final: [M(0, 2, 1)],
  },

  2006: {
    host: "Germany",
    hostFlag: "🇩🇪",
    goldenBoot: { name: "Miroslav Klose", goals: 5 },
    goldenGlove: { name: "Gianluigi Buffon" },
    quote: "Zidane's headbutt.",
    teams: [
      "GER",
      "SWE",
      "ARG",
      "MEX",
      "ITA",
      "AUS",
      "SUI",
      "UKR",
      "ENG",
      "ECU",
      "POR",
      "NED",
      "BRA",
      "GHA",
      "ESP",
      "FRA",
    ],
    r16: [
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(1, 0, 0),
      M(0, 0, 1, "0-3"),
      M(1, 0, 0),
      M(1, 0, 0),
      M(3, 0, 0),
      M(1, 3, 1),
    ],
    qf: [M(1, 1, 0, "4-2"), M(3, 0, 0), M(0, 0, 1, "1-3"), M(0, 1, 1)],
    sf: [M(0, 2, 1, null, "a.e.t."), M(0, 1, 1)],
    final: [M(1, 1, 0, "5-3")],
  },

  2010: {
    host: "South Africa",
    hostFlag: "🇿🇦",
    goldenBoot: { name: "Thomas Müller", goals: 5 },
    goldenGlove: { name: "Iker Casillas" },
    quote: "Iniesta, forever.",
    teams: [
      "URU",
      "KOR",
      "USA",
      "GHA",
      "NED",
      "SVK",
      "BRA",
      "CHI",
      "GER",
      "ENG",
      "ARG",
      "MEX",
      "PAR",
      "JPN",
      "ESP",
      "POR",
    ],
    r16: [
      M(2, 1, 0),
      M(1, 2, 1, null, "a.e.t."),
      M(2, 1, 0),
      M(3, 0, 0),
      M(4, 1, 0),
      M(3, 1, 0),
      M(0, 0, 0, "5-3"),
      M(1, 0, 0),
    ],
    qf: [
      M(1, 1, 0, "4-2", " a.e.t."),
      M(2, 1, 0),
      M(4, 0, 0),
      M(0, 1, 1),
    ],
    sf: [M(2, 3, 1), M(0, 1, 1)],
    final: [M(0, 1, 1, null, "a.e.t.")],
  },

  2014: {
    host: "Brazil",
    hostFlag: "🇧🇷",
    goldenBoot: { name: "James Rodríguez", goals: 6 },
    goldenGlove: { name: "Manuel Neuer" },
    quote: "Götze seals the fourth star.",
    teams: [
      "BRA",
      "CHI",
      "COL",
      "URU",
      "FRA",
      "NGA",
      "GER",
      "ALG",
      "NED",
      "MEX",
      "CRC",
      "GRE",
      "ARG",
      "SUI",
      "BEL",
      "USA",
    ],
    r16: [
      M(1, 1, 0, "3-2"),
      M(2, 0, 0),
      M(2, 0, 0),
      M(2, 1, 0, null, "a.e.t."),
      M(2, 1, 0),
      M(1, 1, 0, "5-3"),
      M(1, 0, 0, null, "a.e.t."),
      M(2, 1, 0, null, "a.e.t."),
    ],
    qf: [M(2, 1, 0), M(0, 1, 1), M(0, 0, 0, "4-3"), M(1, 0, 0)],
    sf: [M(1, 7, 1), M(0, 0, 1, "2-4")],
    final: [M(1, 0, 0, null, "a.e.t.")],
  },

  2018: {
    host: "Russia",
    hostFlag: "🇷🇺",
    goldenBoot: { name: "Harry Kane", goals: 6 },
    goldenGlove: { name: "Thibaut Courtois" },
    quote: "Mbappé arrives.",
    teams: [
      "URU",
      "POR",
      "FRA",
      "ARG",
      "BRA",
      "MEX",
      "BEL",
      "JPN",
      "SWE",
      "SUI",
      "COL",
      "ENG",
      "ESP",
      "RUS",
      "CRO",
      "DEN",
    ],
    r16: [
      M(2, 1, 0),
      M(4, 3, 0),
      M(2, 0, 0),
      M(3, 2, 0),
      M(1, 0, 0),
      M(1, 1, 1, "3-4"),
      M(1, 1, 1, "3-4"),
      M(1, 1, 0, "3-2"),
    ],
    qf: [M(0, 2, 1), M(1, 2, 1), M(0, 2, 1), M(2, 2, 1, "3-4")],
    sf: [M(1, 0, 0), M(1, 2, 1, null, "a.e.t.")],
    final: [M(4, 2, 0)],
  },

  2022: {
    host: "Qatar",
    hostFlag: "🇶🇦",
    goldenBoot: { name: "Kylian Mbappé", goals: 8 },
    goldenGlove: { name: "Emiliano Martínez" },
    quote: "Messi. At last.",
    teams: [
      "NED",
      "USA",
      "ARG",
      "AUS",
      "JPN",
      "CRO",
      "BRA",
      "KOR",
      "MAR",
      "ESP",
      "POR",
      "SUI",
      "ENG",
      "SEN",
      "FRA",
      "POL",
    ],
    r16: [
      M(3, 1, 0),
      M(2, 1, 0),
      M(1, 1, 1, "1-3"),
      M(4, 1, 0),
      M(0, 0, 0, "3-0"),
      M(6, 1, 0),
      M(3, 0, 0),
      M(3, 1, 0),
    ],
    qf: [M(2, 2, 1, "3-4"), M(1, 1, 0, "4-2"), M(1, 0, 0), M(1, 2, 1)],
    sf: [M(3, 0, 0), M(0, 2, 1)],
    tp: M(2, 1, 0),
    final: [M(3, 3, 0, "4-2")],
  },

  2026: {
    host: "USA · Canada · Mexico",
    hostFlag: "🇺🇸 🇨🇦 🇲🇽",
    goldenBoot: null,
    quote: null,
    seeded: false,
    // Sourced from openfootball (github.com/openfootball/world-cup,
    // 2026--usa/cup_finals.txt) — hand-curated, clean names, complete scorers.
    // Bracket-feed order follows the file's "W74 / W77" feeder labels.
    teams: [
      "PAR", "FRA",
      "CAN", "MAR",
      "POR", "ESP",
      "USA", "BEL",
      "BRA", "NOR",
      "MEX", "ENG",
      "ARG", "EGY",
      "SUI", "COL",
    ],
    r32: [
      { ta: "GER", tb: "PAR", s: [1, 1], w: 1, p: "3-4", g: [["Kai Havertz 54'"], ["Julio Enciso 42'"]], date: "Jun 29 · 16:30" },
      { ta: "FRA", tb: "SWE", s: [3, 0], w: 0, g: [["Kylian Mbappé 45'", "Bradley Barcola 53'", "Kylian Mbappé 74'"], []], date: "Jun 30 · 17:00" },
      { ta: "RSA", tb: "CAN", s: [0, 1], w: 1, g: [[], ["Stephen Eustáquio 90+2'"]], date: "Jun 28 · 12:00" },
      { ta: "NED", tb: "MAR", s: [1, 3], w: 1, g: [["Cody Gakpo 72'"], ["Ismael Saibari 35'", "Issa Diop 90+1'", "Ismael Saibari 90+5'"]], date: "Jun 29 · 19:00" },
      { ta: "BRA", tb: "JPN", s: [2, 1], w: 0, g: [["Casemiro 56'", "Gabriel Martinelli 90+5'"], ["Kaishū Sano 29'"]], date: "Jun 29 · 12:00" },
      { ta: "CIV", tb: "NOR", s: [1, 2], w: 1, g: [["Amad Diallo 74'"], ["Antonio Nusa 39'", "Erling Haaland 86'"]], date: "Jun 30 · 12:00" },
      { ta: "MEX", tb: "ECU", s: [2, 0], w: 0, g: [["Julián Quiñones 31'", "Raúl Jiménez 45+1'"], []], date: "Jun 30 · 19:00" },
      { ta: "ENG", tb: "COD", s: [2, 1], w: 0, g: [["Harry Kane 75'", "Harry Kane 86'"], ["Brian Cipenga 7'"]], date: "Jul 1 · 12:00" },
      { ta: "POR", tb: "CRO", s: [2, 1], w: 0, g: [["Cristiano Ronaldo 68' (pen.)", "Gonçalo Ramos 90+4'"], ["Ivan Perišić 53'"]], date: "Jul 2 · 19:00" },
      { ta: "ESP", tb: "AUT", s: [3, 0], w: 0, g: [["Mikel Oyarzabal 36'", "Pedro Porro 66'", "Mikel Oyarzabal 89'"], []], date: "Jul 2 · 12:00" },
      { ta: "USA", tb: "BIH", s: [2, 0], w: 0, g: [["Folarin Balogun 45'", "Malik Tillman 82'"], []], date: "Jul 1 · 17:00" },
      { ta: "BEL", tb: "SEN", s: [3, 2], w: 0, x: "a.e.t.", g: [["Romelu Lukaku 86'", "Youri Tielemans 89'", "Youri Tielemans 120+5' (pen.)"], ["Habib Diarra 25'", "Ismaïla Sarr 51'"]], date: "Jul 1 · 13:00" },
      { ta: "ARG", tb: "CPV", s: [3, 2], w: 0, x: "a.e.t.", g: [["Lionel Messi 29'", "Lisandro Martínez 92'", "Diney Borges 111' (o.g.)"], ["Deroy Duarte 59'", "Sidny Lopes Cabral 103'"]], date: "Jul 3 · 18:00" },
      { ta: "AUS", tb: "EGY", s: [1, 1], w: 1, p: "2-4", g: [["Mohamed Hany 55' (o.g.)"], ["Emam Ashour 13'"]], date: "Jul 3 · 13:00" },
      { ta: "SUI", tb: "ALG", s: [2, 0], w: 0, g: [["Breel Embolo 10'", "Dan Ndoye 46'"], []], date: "Jul 2 · 20:00" },
      { ta: "COL", tb: "GHA", s: [1, 0], w: 0, g: [["Jhon Arias 14'"], []], date: "Jul 3 · 20:30" },
    ],
    r16: [
      // France 1–0 Paraguay (R16, Jul 4) — France advance
      M(0, 1, 1, null, null, [[], ["Kylian Mbappé 70' (pen.)"]]),
      M(0, 4, 1, null, null, [[], ["Ismael Saibari 23'", "Azzedine Ounahi 50'", "Azzedine Ounahi 82'", "Soufiane Rahimi 90+8'"]]),
      // Portugal 0–1 Spain (R16, Jul 6) — Spain advance on Merino's stoppage-time winner
      M(0, 1, 1, null, null, [[], ["Mikel Merino 90+1'"]]),
      // USA 1–4 Belgium (R16, Jul 6) — Belgium advance (De Ketelaere brace)
      M(1, 4, 1, null, null, [["Malik Tillman 31'"], ["Charles De Ketelaere 9'", "Charles De Ketelaere 33'", "Hans Vanaken 57'", "Romelu Lukaku 90+3'"]]),
      M(1, 2, 1, null, null, [["Neymar 90+10' (pen.)"], ["Erling Haaland 79'", "Erling Haaland 90'"]]),
      // Mexico 2–3 England (R16, Jul 5) — England advance
      M(2, 3, 1, null, null, [["Julián Quiñones 42'", "Raúl Jiménez 69' (pen.)"], ["Jude Bellingham 36'", "Jude Bellingham 38'", "Harry Kane 60' (pen.)"]]),
      // Argentina 3–2 Egypt (R16, Jul 7) — Argentina advance after a 2-goal comeback
      M(3, 2, 0, null, null, [["Cristian Romero 79'", "Lionel Messi 83'", "Enzo Fernández 90+2'"], ["Yasser Ibrahim 15'", "Mostafa Zico 67'"]]),
      // Switzerland 0–0 Colombia (R16, Jul 8) — SUI wins 4-3 on pens
      M(0, 0, 0, "4-3", "a.e.t.", null),
    ],
    qf: [
      // France 2–0 Morocco (QF, Jul 10) — France advance (Mbappé, Dembélé)
      M(2, 0, 0, null, null, [["Kylian Mbappé 60'", "Ousmane Dembélé 66'"], []]),
      // Spain 2–1 Belgium (QF, Jul 10) — Spain advance (Fabián Ruiz, Merino; De Ketelaere)
      M(2, 1, 0, null, null, [["Fabián Ruiz 30'", "Mikel Merino 88'"], ["Charles De Ketelaere 41'"]]),
      // Norway 1–2 England (QF, Jul 11, a.e.t.) — England advance (Schjelderup; Bellingham 2)
      M(1, 2, 1, null, "a.e.t.", [["Andreas Schjelderup 36'"], ["Jude Bellingham 45+2'", "Jude Bellingham 93'"]]),
      // Argentina 3–1 Switzerland (QF, Jul 11, a.e.t.) — Argentina advance; Embolo sent off (2nd yellow)
      M(3, 1, 0, null, "a.e.t.", [["Alexis Mac Allister 11'", "Julián Álvarez 112'", "Lautaro Martínez 120+2'"], ["Dan Ndoye 67'"]]),
    ],
    sf: [
      // France 0–2 Spain (SF, Jul 14) — Spain advance to final (Oyarzabal pen., Porro)
      M(0, 2, 1, null, null, [[], ["Mikel Oyarzabal 22' (pen.)", "Pedro Porro 58'"]]),
      // England 1–2 Argentina (SF, Jul 15) — Argentina rally late (Messi 2 assists) to reach the final
      M(1, 2, 1, null, null, [["Anthony Gordon 55'"], ["Enzo Fernández 85'", "Lautaro Martínez 90+2'"]]),
    ],
    // Third-place play-off: France 4–6 England (SF losers) — England take the bronze in a ten-goal thriller
    tp: M(4, 6, 1, null, null, [
      ["Kylian Mbappé 14'", "Ousmane Dembélé 33'", "Kylian Mbappé 58'", "Michael Olise 71'"],
      ["Jude Bellingham 9'", "Harry Kane 27' (pen.)", "Bukayo Saka 45+2'", "Harry Kane 63'", "Phil Foden 79'", "Jude Bellingham 88'"],
    ]),
    final: null,
  },
};
