// Auto-generated by scripts/fetch-highlights.ts — DO NOT EDIT BY HAND.
// Keyed `${year}_${teamA}_${teamB}`. lookup tries both orientations.

export interface Highlight {
  videoId: string;
  title: string;
  thumbnail: string;
}

const HIGHLIGHTS: Record<string, Highlight> = {
  "1930_ARG_CHI": { videoId: "drQhxpdW3Oc", title: "1930 WC G1 Argentina - Chile (Montevideo, 22.7.1930)", thumbnail: "https://i.ytimg.com/vi/drQhxpdW3Oc/hqdefault.jpg" },
  "1930_USA_BEL": { videoId: "h6j1iN1IP9s", title: "USA 🇺🇸 3–0 Belgium 🇧🇪 | 1930 FIFA World Cup 🔥 Remembering America’s Forgotten Legends 🕊️", thumbnail: "https://i.ytimg.com/vi/h6j1iN1IP9s/hqdefault.jpg" },
  "1930_URU_PER": { videoId: "LBhirjwWs0Y", title: "1930 WC G3 Uruguay - Peru (Montevideo, 18.7.1930)", thumbnail: "https://i.ytimg.com/vi/LBhirjwWs0Y/hqdefault.jpg" },
  "1930_YUG_BOL": { videoId: "KohSdJRe9TE", title: "1930 WC G2 Brazil - Bolivia (Montevideo, 20.7.1930)", thumbnail: "https://i.ytimg.com/vi/KohSdJRe9TE/hqdefault.jpg" },
  "1930_ARG_USA": { videoId: "3gELBavbzWQ", title: "1930 WORLD CUP FINAL: Uruguay 4-2 Argentina", thumbnail: "https://i.ytimg.com/vi/3gELBavbzWQ/hqdefault.jpg" },
  "1930_URU_YUG": { videoId: "-3-oRADPFHo", title: "1930 WC SF Uruguay - Yugoslavia (Montevideo, 27.7.1930)", thumbnail: "https://i.ytimg.com/vi/-3-oRADPFHo/hqdefault.jpg" },
  "1930_ARG_URU": { videoId: "3gELBavbzWQ", title: "1930 WORLD CUP FINAL: Uruguay 4-2 Argentina", thumbnail: "https://i.ytimg.com/vi/3gELBavbzWQ/hqdefault.jpg" },
  "1934_ITA_USA": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1934_ESP_BRA": { videoId: "ZX1QvcTdWUk", title: "1934 WC R1 Spain - Brazil (Genoa, 27.5.1934)", thumbnail: "https://i.ytimg.com/vi/ZX1QvcTdWUk/hqdefault.jpg" },
  "1934_AUT_FRA": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1934_HUN_EGY": { videoId: "1jun-30nIdI", title: "1934 WC R1 Hungary - Egypt (Naples, 27.5.1934)", thumbnail: "https://i.ytimg.com/vi/1jun-30nIdI/hqdefault.jpg" },
  "1934_TCH_SUI": { videoId: "CKmfqVoygiA", title: "WC 1934 Switzerland vs. Netherlands 3-2 (27.05.1934)", thumbnail: "https://i.ytimg.com/vi/CKmfqVoygiA/hqdefault.jpg" },
  "1934_GER_BEL": { videoId: "SfhFoXUeGms", title: "1934 WC R1 Germany - Belgium (Florence, 27.5.1934)", thumbnail: "https://i.ytimg.com/vi/SfhFoXUeGms/hqdefault.jpg" },
  "1934_SWE_ARG": { videoId: "IqP7ylpkJEA", title: "1934 WC R1 Sweden - Argentina (Bologna, 27.5.1934)", thumbnail: "https://i.ytimg.com/vi/IqP7ylpkJEA/hqdefault.jpg" },
  "1934_NED_ROU": { videoId: "CKmfqVoygiA", title: "WC 1934 Switzerland vs. Netherlands 3-2 (27.05.1934)", thumbnail: "https://i.ytimg.com/vi/CKmfqVoygiA/hqdefault.jpg" },
  "1934_ITA_ESP": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1934_AUT_HUN": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1934_TCH_GER": { videoId: "k2Lj7jzJWhc", title: "1934 WC SF Czechoslovakia - Germany (Rome, 3.6.1934)", thumbnail: "https://i.ytimg.com/vi/k2Lj7jzJWhc/hqdefault.jpg" },
  "1934_SWE_NED": { videoId: "CKmfqVoygiA", title: "WC 1934 Switzerland vs. Netherlands 3-2 (27.05.1934)", thumbnail: "https://i.ytimg.com/vi/CKmfqVoygiA/hqdefault.jpg" },
  "1934_ITA_AUT": { videoId: "Hc714kI9EOQ", title: "1934 World Cup .. Italy - Austria 1-0", thumbnail: "https://i.ytimg.com/vi/Hc714kI9EOQ/hqdefault.jpg" },
  "1934_TCH_SWE": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1934_ITA_TCH": { videoId: "EBwZv0eFrCM", title: "1934 WORLD CUP FINAL: Italy 2-1 Czechoslovakia (AET)", thumbnail: "https://i.ytimg.com/vi/EBwZv0eFrCM/hqdefault.jpg" },
  "1938_SWE_AUT": { videoId: "ocaP0NySEbA", title: "QWC 1938 Germany vs. Sweden 5-0 (21.11.1937)", thumbnail: "https://i.ytimg.com/vi/ocaP0NySEbA/hqdefault.jpg" },
  "1938_CUB_ROU": { videoId: "GUXQdAfHVzc", title: "1938 WC R1 Cuba-  Romania (Toulouse,5.6.1938)", thumbnail: "https://i.ytimg.com/vi/GUXQdAfHVzc/hqdefault.jpg" },
  "1938_HUN_IDN": { videoId: "dbJIqjny2Jk", title: "1938 WORLD CUP FINAL: Italy 4-2 Hungary", thumbnail: "https://i.ytimg.com/vi/dbJIqjny2Jk/hqdefault.jpg" },
  "1938_GER_SUI": { videoId: "d16NaAzqKek", title: "WC 1938 Switzerland vs. Germany 4-2 (09.06.1938) (re-upload)", thumbnail: "https://i.ytimg.com/vi/d16NaAzqKek/hqdefault.jpg" },
  "1938_FRA_BEL": { videoId: "IHdLy-cr59I", title: "1938 WC R1 France - Belgium (Paris, 5.6.1938)", thumbnail: "https://i.ytimg.com/vi/IHdLy-cr59I/hqdefault.jpg" },
  "1938_ITA_NOR": { videoId: "XqBmUBhCeJs", title: "WC 1938 Italy vs. Norway 2-1 (05.06.1938)", thumbnail: "https://i.ytimg.com/vi/XqBmUBhCeJs/hqdefault.jpg" },
  "1938_BRA_POL": { videoId: "Z8e5pZpUx6w", title: "1938 World Cup .. Brazil - Poland 6-5 aet", thumbnail: "https://i.ytimg.com/vi/Z8e5pZpUx6w/hqdefault.jpg" },
  "1938_TCH_NED": { videoId: "jEZmkwpelzM", title: "WC 1938 Czechoslovakia vs. Netherlands 3-0 (05.06.1938) (re-upload)", thumbnail: "https://i.ytimg.com/vi/jEZmkwpelzM/hqdefault.jpg" },
  "1938_SWE_CUB": { videoId: "SKWqxADbDok", title: "WC 1938 1/4 Sweden - Cuba (12.06.1938)", thumbnail: "https://i.ytimg.com/vi/SKWqxADbDok/hqdefault.jpg" },
  "1938_HUN_SUI": { videoId: "5cVrWymwsRg", title: "West Germany - Hungary WORLD CUP 1954 final | AI colourized 60 fps |", thumbnail: "https://i.ytimg.com/vi/5cVrWymwsRg/hqdefault.jpg" },
  "1938_FRA_ITA": { videoId: "dbJIqjny2Jk", title: "1938 WORLD CUP FINAL: Italy 4-2 Hungary", thumbnail: "https://i.ytimg.com/vi/dbJIqjny2Jk/hqdefault.jpg" },
  "1938_BRA_TCH": { videoId: "CblRAu0fMTA", title: "1938 World Cup .. Brazil - Czechoslovakia 1-1", thumbnail: "https://i.ytimg.com/vi/CblRAu0fMTA/hqdefault.jpg" },
  "1938_SWE_HUN": { videoId: "1rYcxR345VA", title: "WC 1938 Hungary vs. Sweden 5-1 (16.06.1938)", thumbnail: "https://i.ytimg.com/vi/1rYcxR345VA/hqdefault.jpg" },
  "1938_ITA_BRA": { videoId: "dbJIqjny2Jk", title: "1938 WORLD CUP FINAL: Italy 4-2 Hungary", thumbnail: "https://i.ytimg.com/vi/dbJIqjny2Jk/hqdefault.jpg" },
  "1938_HUN_ITA": { videoId: "dbJIqjny2Jk", title: "1938 WORLD CUP FINAL: Italy 4-2 Hungary", thumbnail: "https://i.ytimg.com/vi/dbJIqjny2Jk/hqdefault.jpg" },
  "1950_URU_BOL": { videoId: "Pu1WanatiAM", title: "1950 WORLD CUP FINAL MATCH: Uruguay 2-1 Brazil", thumbnail: "https://i.ytimg.com/vi/Pu1WanatiAM/hqdefault.jpg" },
  "1950_SWE_ITA": { videoId: "VWE97MIPSLQ", title: "1950 (June 25) Sweden 3-Italy 2 (World Cup).mpg", thumbnail: "https://i.ytimg.com/vi/VWE97MIPSLQ/hqdefault.jpg" },
  "1950_BRA_YUG": { videoId: "Pu1WanatiAM", title: "1950 WORLD CUP FINAL MATCH: Uruguay 2-1 Brazil", thumbnail: "https://i.ytimg.com/vi/Pu1WanatiAM/hqdefault.jpg" },
  "1950_ESP_ENG": { videoId: "n93Q4gUNs9A", title: "WC 1950 Spain vs. England 1-0 (02.07.1950)", thumbnail: "https://i.ytimg.com/vi/n93Q4gUNs9A/hqdefault.jpg" },
  "1950_URU_SWE": { videoId: "Pu1WanatiAM", title: "1950 WORLD CUP FINAL MATCH: Uruguay 2-1 Brazil", thumbnail: "https://i.ytimg.com/vi/Pu1WanatiAM/hqdefault.jpg" },
  "1950_BRA_ESP": { videoId: "nEsXmcznteI", title: "1950 WC FP Brazil - Spain (Rio de Janeiro, 13.7.1950)", thumbnail: "https://i.ytimg.com/vi/nEsXmcznteI/hqdefault.jpg" },
  "1950_URU_BRA": { videoId: "Pu1WanatiAM", title: "1950 WORLD CUP FINAL MATCH: Uruguay 2-1 Brazil", thumbnail: "https://i.ytimg.com/vi/Pu1WanatiAM/hqdefault.jpg" },
  "1954_FRG_YUG": { videoId: "hVtwJua_mOc", title: "WC 1954 West Germany vs. Yugoslavia 2-0 (27.06.1954)", thumbnail: "https://i.ytimg.com/vi/hVtwJua_mOc/hqdefault.jpg" },
  "1954_AUT_SUI": { videoId: "T-BQWvSyIyI", title: "Quarter-finals austria 7-5 switzerland 26 june 1954", thumbnail: "https://i.ytimg.com/vi/T-BQWvSyIyI/hqdefault.jpg" },
  "1954_HUN_BRA": { videoId: "O_NsylAxUkY", title: "1954.07.26. Hungary v Brazil 4-2 (Hightlights)", thumbnail: "https://i.ytimg.com/vi/O_NsylAxUkY/hqdefault.jpg" },
  "1954_URU_ENG": { videoId: "UatVIfbIZVU", title: "Uruguay 4-2 England | 1954 World Cup | Match Highlights", thumbnail: "https://i.ytimg.com/vi/UatVIfbIZVU/hqdefault.jpg" },
  "1954_FRG_AUT": { videoId: "5cVrWymwsRg", title: "West Germany - Hungary WORLD CUP 1954 final | AI colourized 60 fps |", thumbnail: "https://i.ytimg.com/vi/5cVrWymwsRg/hqdefault.jpg" },
  "1954_HUN_URU": { videoId: "Hwvr0Rzy81M", title: "Semi-finals Hungary 4–2 Uruguay 30 June 1954", thumbnail: "https://i.ytimg.com/vi/Hwvr0Rzy81M/hqdefault.jpg" },
  "1954_FRG_HUN": { videoId: "5cVrWymwsRg", title: "West Germany - Hungary WORLD CUP 1954 final | AI colourized 60 fps |", thumbnail: "https://i.ytimg.com/vi/5cVrWymwsRg/hqdefault.jpg" },
  "1958_BRA_WAL": { videoId: "JE2xPzeSiBc", title: "1958 WORLD CUP FINAL: Brazil 5-2 Sweden", thumbnail: "https://i.ytimg.com/vi/JE2xPzeSiBc/hqdefault.jpg" },
  "1958_FRA_NIR": { videoId: "isQuLhaf26o", title: "Quarter-finals: France 4–0 Northern Ireland 19 June 1958", thumbnail: "https://i.ytimg.com/vi/isQuLhaf26o/hqdefault.jpg" },
  "1958_SWE_URS": { videoId: "npeQxdYwvrc", title: "Quarter final: Sweden 2–0 Soviet Union 19 June 1958", thumbnail: "https://i.ytimg.com/vi/npeQxdYwvrc/hqdefault.jpg" },
  "1958_FRG_YUG": { videoId: "3iC4qfyn5yc", title: "Quarter final: West Germany 1–0 Yugoslavia 19 June 1958", thumbnail: "https://i.ytimg.com/vi/3iC4qfyn5yc/hqdefault.jpg" },
  "1958_BRA_FRA": { videoId: "CMO7_qXT4so", title: "Brazil 5x2 France Highlights (1958 World Cup - Semi-final)", thumbnail: "https://i.ytimg.com/vi/CMO7_qXT4so/hqdefault.jpg" },
  "1958_SWE_FRG": { videoId: "O0yIJyoUDUc", title: "World Cup 1958  GER vs. SWE", thumbnail: "https://i.ytimg.com/vi/O0yIJyoUDUc/hqdefault.jpg" },
  "1958_BRA_SWE": { videoId: "JE2xPzeSiBc", title: "1958 WORLD CUP FINAL: Brazil 5-2 Sweden", thumbnail: "https://i.ytimg.com/vi/JE2xPzeSiBc/hqdefault.jpg" },
  "1962_BRA_ENG": { videoId: "ra6DfEYMEyw", title: "Brazil vs England - WC 1962 QF", thumbnail: "https://i.ytimg.com/vi/ra6DfEYMEyw/hqdefault.jpg" },
  "1962_CHI_URS": { videoId: "xGwZL_XTpqo", title: "1962 (June 10) Chile 2-USSR 1 (World Cup).mpg", thumbnail: "https://i.ytimg.com/vi/xGwZL_XTpqo/hqdefault.jpg" },
  "1962_TCH_HUN": { videoId: "fxK5nYk35eA", title: "1962 (June 10) Czechoslovakia 1-Hungary 0 (World Cup).mpg", thumbnail: "https://i.ytimg.com/vi/fxK5nYk35eA/hqdefault.jpg" },
  "1962_YUG_FRG": { videoId: "kOSrXXT-Y-A", title: "Yugoslavia v Germany 1962", thumbnail: "https://i.ytimg.com/vi/kOSrXXT-Y-A/hqdefault.jpg" },
  "1962_BRA_CHI": { videoId: "FnV_ezpSMI0", title: "1962 WORLD CUP FINAL: Brazil 3-1 Czechoslovakia", thumbnail: "https://i.ytimg.com/vi/FnV_ezpSMI0/hqdefault.jpg" },
  "1962_TCH_YUG": { videoId: "FnV_ezpSMI0", title: "1962 WORLD CUP FINAL: Brazil 3-1 Czechoslovakia", thumbnail: "https://i.ytimg.com/vi/FnV_ezpSMI0/hqdefault.jpg" },
  "1962_BRA_TCH": { videoId: "FnV_ezpSMI0", title: "1962 WORLD CUP FINAL: Brazil 3-1 Czechoslovakia", thumbnail: "https://i.ytimg.com/vi/FnV_ezpSMI0/hqdefault.jpg" },
  "1966_ENG_ARG": { videoId: "aq0nxUlgXm8", title: "England v Argentina 1-0 World Cup Quarter Finals 1966", thumbnail: "https://i.ytimg.com/vi/aq0nxUlgXm8/hqdefault.jpg" },
  "1966_POR_PRK": { videoId: "frx-u3T5eT4", title: "Greatest Matches Ep1: World Cup 1966  Portugal - North Korea 5-3", thumbnail: "https://i.ytimg.com/vi/frx-u3T5eT4/hqdefault.jpg" },
  "1966_FRG_URU": { videoId: "XUKc9lpmcqI", title: "Germany - Uruguay 4-0. 1966 World cup quarterfinal", thumbnail: "https://i.ytimg.com/vi/XUKc9lpmcqI/hqdefault.jpg" },
  "1966_URS_HUN": { videoId: "UzpX-3dvkb4", title: "USSR HUNGARY 1_4 FINAL WORLD CUP 1966", thumbnail: "https://i.ytimg.com/vi/UzpX-3dvkb4/hqdefault.jpg" },
  "1966_ENG_POR": { videoId: "myG7PSY2auk", title: "England 2-1 Portugal (1966 World Cup)", thumbnail: "https://i.ytimg.com/vi/myG7PSY2auk/hqdefault.jpg" },
  "1966_FRG_URS": { videoId: "hEbCSqFsu9w", title: "West Germany vs Soviet Union 2-1 - 1966 FIFA World Cup Highlights (Semi-finals)", thumbnail: "https://i.ytimg.com/vi/hEbCSqFsu9w/hqdefault.jpg" },
  "1966_ENG_FRG": { videoId: "VPQvekloS8U", title: "England 4-2 West Germany | 1966 FIFA World Cup Final | Highlights", thumbnail: "https://i.ytimg.com/vi/VPQvekloS8U/hqdefault.jpg" },
  "1970_URU_URS": { videoId: "T9mh-u3Y8X4", title: "1970 (June 14) Uruguay 1-USSR 0 (World Cup).mpg", thumbnail: "https://i.ytimg.com/vi/T9mh-u3Y8X4/hqdefault.jpg" },
  "1970_ITA_MEX": { videoId: "kBJVZ5k-F3M", title: "1970 WORLD CUP FINAL: Brazil 4-1 Italy", thumbnail: "https://i.ytimg.com/vi/kBJVZ5k-F3M/hqdefault.jpg" },
  "1970_FRG_ENG": { videoId: "DIxr3kQnYvk", title: "Italy 4-3 West Germany | Extended Highlights | 1970 FIFA World Cup", thumbnail: "https://i.ytimg.com/vi/DIxr3kQnYvk/hqdefault.jpg" },
  "1970_BRA_URU": { videoId: "WDguEvAsweQ", title: "Brazil 3-1 Uruguay | Extended Highlights | 1970 FIFA World Cup", thumbnail: "https://i.ytimg.com/vi/WDguEvAsweQ/hqdefault.jpg" },
  "1970_ITA_FRG": { videoId: "DIxr3kQnYvk", title: "Italy 4-3 West Germany | Extended Highlights | 1970 FIFA World Cup", thumbnail: "https://i.ytimg.com/vi/DIxr3kQnYvk/hqdefault.jpg" },
  "1974_FRG_YUG": { videoId: "ABVzpxd1-q4", title: "West germany vs Yugoslavia 2 - 0 ( Exclu ) World Cup 74 HD Quality", thumbnail: "https://i.ytimg.com/vi/ABVzpxd1-q4/hqdefault.jpg" },
  "1974_POL_SWE": { videoId: "D2yVSWVQDDI", title: "Poland vs italy 2 - 1 Best Of Moments World Cup 74 High Quality", thumbnail: "https://i.ytimg.com/vi/D2yVSWVQDDI/hqdefault.jpg" },
  "1974_BRA_GDR": { videoId: "avrOH4RN1ug", title: "Brazil - Yugoslavia World Cup 1974 | Full highlight - 1080p HD | Roberto Rivelino", thumbnail: "https://i.ytimg.com/vi/avrOH4RN1ug/hqdefault.jpg" },
  "1974_FRG_NED": { videoId: "KpUCKi4yvuU", title: "Germany vs Netherlands 2 - 1 | 1974 World Cup Final Highlights &amp; Goals - HD720p", thumbnail: "https://i.ytimg.com/vi/KpUCKi4yvuU/hqdefault.jpg" },
  "1978_BRA_PER": { videoId: "7YTQ-a9LnDI", title: "Brazil 3-0 Peru world cup 1978 | Full highlight | 1080p HD | Dirceu - Teofilo Cubillas", thumbnail: "https://i.ytimg.com/vi/7YTQ-a9LnDI/hqdefault.jpg" },
  "1982_POL_BEL": { videoId: "CIHP8NQX4Pc", title: "BONIEK - against belgium 1982 (x 3)", thumbnail: "https://i.ytimg.com/vi/CIHP8NQX4Pc/hqdefault.jpg" },
  "1982_ITA_ARG": { videoId: "ReCyvs5alLs", title: "Italy 2-1 Argentina world cup 1982 | Full highlight | 1080p HD | Paolo Rossi | Maradona | Kempes", thumbnail: "https://i.ytimg.com/vi/ReCyvs5alLs/hqdefault.jpg" },
  "1982_FRG_ESP": { videoId: "HmhlzsAxg_o", title: "West Germany 2-1 Spain | 1982 World Cup Group B Match | Highlights &amp; Best Moments", thumbnail: "https://i.ytimg.com/vi/HmhlzsAxg_o/hqdefault.jpg" },
  "1982_FRA_NIR": { videoId: "r6tyZl7L4Qk", title: "France - Northern Ireland ●World Cup 1982 | Full highlight - 1080p HD", thumbnail: "https://i.ytimg.com/vi/r6tyZl7L4Qk/hqdefault.jpg" },
  "1986_BRA_POL": { videoId: "K726pfbVRW0", title: "Brazil 4-0 Poland World Cup 1986 | Full highlight -1080p HD | Zico", thumbnail: "https://i.ytimg.com/vi/K726pfbVRW0/hqdefault.jpg" },
  "1986_MEX_BUL": { videoId: "nzgxThtwUHM", title: "Mexico VS Bulgaria Gol de tijera de Manuel Negrete Mexico 86", thumbnail: "https://i.ytimg.com/vi/nzgxThtwUHM/hqdefault.jpg" },
  "1986_ARG_URU": { videoId: "n5KDJOIJ2r0", title: "Argentina 1-0 Uruguay World Cup 1986 | Full highlight | 1080p HD - Diego Maradona", thumbnail: "https://i.ytimg.com/vi/n5KDJOIJ2r0/hqdefault.jpg" },
  "1986_BEL_URS": { videoId: "5K9R8BLHOXs", title: "Soviet Union 3-4 Belgium world cup 1986 | Full highlight | 1080p HD", thumbnail: "https://i.ytimg.com/vi/5K9R8BLHOXs/hqdefault.jpg" },
  "1986_ESP_DEN": { videoId: "do4tdtXyn18", title: "Spain 5-1 Denmark world cup 1986 | Full highlight | 1080p HD - Butragueño", thumbnail: "https://i.ytimg.com/vi/do4tdtXyn18/hqdefault.jpg" },
  "1986_FRA_FRG": { videoId: "3_TcUTmidVg", title: "Germany 2-0 France Semi Finals World cup 1986 | Full highlight | 1080p HD", thumbnail: "https://i.ytimg.com/vi/3_TcUTmidVg/hqdefault.jpg" },
  "1990_YUG_ESP": { videoId: "k3EK4JLImm0", title: "Yugoslavia 2-1 Spain World Cup 1990 | Full highlight | 1080p HD", thumbnail: "https://i.ytimg.com/vi/k3EK4JLImm0/hqdefault.jpg" },
  "1990_ENG_BEL": { videoId: "BHq4Jydj4oY", title: "England - Belgium ●World Cup 1990 | Full highlight - 1080p HD", thumbnail: "https://i.ytimg.com/vi/BHq4Jydj4oY/hqdefault.jpg" },
  "1994_NGA_ITA": { videoId: "YuvNo8Y3GRQ", title: "Italy - Nigeria World Cup 1994 | Full Highlights | FHD 60 fps", thumbnail: "https://i.ytimg.com/vi/YuvNo8Y3GRQ/hqdefault.jpg" },
  "1994_NED_IRL": { videoId: "hMm9DbXGRTc", title: "Republic of Ireland vs Netherlands Round of 16 World cup 1994", thumbnail: "https://i.ytimg.com/vi/hMm9DbXGRTc/hqdefault.jpg" },
  "1998_NED_ARG": { videoId: "DemI2OO7FsU", title: "Netherlands 2-1 Argentina | 1998 World Cup | Match Highlights", thumbnail: "https://i.ytimg.com/vi/DemI2OO7FsU/hqdefault.jpg" },
  "2006_GER_SWE": { videoId: "hEKOOH3vPhI", title: "🇩🇪 ​All of Germany&#39;s 2006 FIFA World Cup Goals | Klose, Podolski, Schweinsteiger and more!", thumbnail: "https://i.ytimg.com/vi/hEKOOH3vPhI/hqdefault.jpg" },
  "2006_ENG_POR": { videoId: "v-6QoG1wz0A", title: "England vs Portugal 2006 World Cup Quarter-Finals H/L", thumbnail: "https://i.ytimg.com/vi/v-6QoG1wz0A/hqdefault.jpg" },

  "2026_GER_PAR": { videoId: "Gw6vNwAvkTs", title: "Highlights | Germany (3)1-1(4) Paraguay | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/Gw6vNwAvkTs/hqdefault.jpg" },

  "2026_FRA_SWE": { videoId: "A7pgChEIFTg", title: "Highlights | France 3-0 Sweden | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/A7pgChEIFTg/hqdefault.jpg" },

  "2026_RSA_CAN": { videoId: "uv-FSqzHXAo", title: "Highlights | South Africa 0-1 Canada | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/uv-FSqzHXAo/hqdefault.jpg" },

  "2026_NED_MAR": { videoId: "vdnhUnGHwco", title: "Highlights | Netherlands (2)1-1(3) Morocco | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/vdnhUnGHwco/hqdefault.jpg" },

  "2026_BRA_JPN": { videoId: "Fd_KYjbmws4", title: "Highlights | Brazil 2-1 Japan | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/Fd_KYjbmws4/hqdefault.jpg" },

  "2026_CIV_NOR": { videoId: "ATzmoebQMj0", title: "Highlights | Cote d&#39;Ivoire 1-2 Norway | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/ATzmoebQMj0/hqdefault.jpg" },

  "2026_MEX_ECU": { videoId: "t-miz8tN7Qw", title: "Highlights | Mexico 2-0 Ecuador |FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/t-miz8tN7Qw/hqdefault.jpg" },

  "2026_ENG_COD": { videoId: "T6MYUQgpCv8", title: "Highlights | England 2-1 Congo DR | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/T6MYUQgpCv8/hqdefault.jpg" },

  "2026_POR_CRO": { videoId: "jxU1VT5YXXE", title: "Highlights | Portugal 2-1 Croatia | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/jxU1VT5YXXE/hqdefault.jpg" },

  "2026_ESP_AUT": { videoId: "p_j4aMfNQyI", title: "Highlights | Spain 3-0 Austria | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/p_j4aMfNQyI/hqdefault.jpg" },

  "2026_USA_BIH": { videoId: "SGQpzA9qcwk", title: "Highlights | USA 2-0 Bosnia And Herzegovina | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/SGQpzA9qcwk/hqdefault.jpg" },

  "2026_BEL_SEN": { videoId: "PsPQkfngzV8", title: "Highlights | Belgium 3-2 Senegal | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/PsPQkfngzV8/hqdefault.jpg" },

  "2026_ARG_CPV": { videoId: "hzvEZ2Vxb94", title: "Highlights | Argentina 3-2 Cabo Verde | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/hzvEZ2Vxb94/hqdefault.jpg" },

  "2026_AUS_EGY": { videoId: "olBx2GK7kZI", title: "Highlights | Australia (2)1-1(4) Egypt | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/olBx2GK7kZI/hqdefault.jpg" },

  "2026_SUI_ALG": { videoId: "-q-nO0sz18s", title: "Highlights | Switzerland 2-0 Algeria | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/-q-nO0sz18s/hqdefault.jpg" },

  "2026_COL_GHA": { videoId: "I43WUQJFfCw", title: "Highlights | Colombia 1-0 Ghana | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/I43WUQJFfCw/hqdefault.jpg" },

  "2026_FRA_PAR": { videoId: "4HZCeb88uSI", title: "Highlights | Paraguay 0-1 France | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/4HZCeb88uSI/hqdefault.jpg" },

  "2026_CAN_MAR": { videoId: "sAYjtcpoaf0", title: "Highlights | Canada 0-3 Morocco | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/sAYjtcpoaf0/hqdefault.jpg" },

  "2026_BRA_NOR": { videoId: "42ovN5rW79U", title: "Highlights | Brazil 1-2 Norway | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/42ovN5rW79U/hqdefault.jpg" },

  "2026_MEX_ENG": { videoId: "ydx1L0aDj_c", title: "Highlights | Mexico 2-3 England | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/ydx1L0aDj_c/hqdefault.jpg" },

  "2026_POR_ESP": { videoId: "iwE1D_JQSQ8", title: "Highlights | Portugal 0-1 Spain | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/iwE1D_JQSQ8/hqdefault.jpg" },

  "2026_USA_BEL": { videoId: "f-HxAza_gus", title: "Alt Cast Highlights: USA v Belgium | FIFA World Cup 2026™", thumbnail: "https://i.ytimg.com/vi/f-HxAza_gus/hqdefault.jpg" },

  "2026_ARG_EGY": { videoId: "Njg9l2VmzjY", title: "Argentina 🆚 Egypt #FIFAWorldCupOnYT", thumbnail: "https://i.ytimg.com/vi/Njg9l2VmzjY/hqdefault.jpg" },
};

export function getHighlights(
  year: number,
  teamA: string,
  teamB: string
): Highlight | null {
  return (
    HIGHLIGHTS[`${year}_${teamA}_${teamB}`] ??
    HIGHLIGHTS[`${year}_${teamB}_${teamA}`] ??
    null
  );
}
